<?php
$country_calling_codes['DZ'] = array('value' =>'213', 'name' =>'Algeria (+213)');
$country_calling_codes['AD'] = array('value' =>'376', 'name' =>'Andorra (+376)');
$country_calling_codes['AO'] = array('value' =>'244', 'name' =>'Angola (+244)');
$country_calling_codes['AI'] = array('value' =>'1264', 'name' =>'Anguilla (+1264)');
$country_calling_codes['AG'] = array('value' =>'1268', 'name' =>'Antigua &amp; Barbuda (+1268)');
$country_calling_codes['AR'] = array('value' =>'54', 'name' =>'Argentina (+54)');
$country_calling_codes['AM'] = array('value' =>'374', 'name' =>'Armenia (+374)');
$country_calling_codes['AW'] = array('value' =>'297', 'name' =>'Aruba (+297)');
$country_calling_codes['AU'] = array('value' =>'61', 'name' =>'Australia (+61)');
$country_calling_codes['AT'] = array('value' =>'43', 'name' =>'Austria (+43)');
$country_calling_codes['AZ'] = array('value' =>'994', 'name' =>'Azerbaijan (+994)');
$country_calling_codes['BS'] = array('value' =>'1242', 'name' =>'Bahamas (+1242)');
$country_calling_codes['BH'] = array('value' =>'973', 'name' =>'Bahrain (+973)');
$country_calling_codes['BD'] = array('value' =>'880', 'name' =>'Bangladesh (+880)');
$country_calling_codes['BB'] = array('value' =>'1246', 'name' =>'Barbados (+1246)');
$country_calling_codes['BY'] = array('value' =>'375', 'name' =>'Belarus (+375)');
$country_calling_codes['BE'] = array('value' =>'32', 'name' =>'Belgium (+32)');
$country_calling_codes['BZ'] = array('value' =>'501', 'name' =>'Belize (+501)');
$country_calling_codes['BJ'] = array('value' =>'229', 'name' =>'Benin (+229)');
$country_calling_codes['BM'] = array('value' =>'1441', 'name' =>'Bermuda (+1441)');
$country_calling_codes['BT'] = array('value' =>'975', 'name' =>'Bhutan (+975)');
$country_calling_codes['BO'] = array('value' =>'591', 'name' =>'Bolivia (+591)');
$country_calling_codes['BA'] = array('value' =>'387', 'name' =>'Bosnia Herzegovina (+387)');
$country_calling_codes['BW'] = array('value' =>'267', 'name' =>'Botswana (+267)');
$country_calling_codes['BR'] = array('value' =>'55', 'name' =>'Brazil (+55)');
$country_calling_codes['BN'] = array('value' =>'673', 'name' =>'Brunei (+673)');
$country_calling_codes['BG'] = array('value' =>'359', 'name' =>'Bulgaria (+359)');
$country_calling_codes['BF'] = array('value' =>'226', 'name' =>'Burkina Faso (+226)');
$country_calling_codes['BI'] = array('value' =>'257', 'name' =>'Burundi (+257)');
$country_calling_codes['KH'] = array('value' =>'855', 'name' =>'Cambodia (+855)');
$country_calling_codes['CM'] = array('value' =>'237', 'name' =>'Cameroon (+237)');
$country_calling_codes['CA'] = array('value' =>'1', 'name' =>'Canada (+1)');
$country_calling_codes['CV'] = array('value' =>'238', 'name' =>'Cape Verde Islands (+238)');
$country_calling_codes['KY'] = array('value' =>'1345', 'name' =>'Cayman Islands (+1345)');
$country_calling_codes['CF'] = array('value' =>'236', 'name' =>'Central African Republic (+236)');
$country_calling_codes['CL'] = array('value' =>'56', 'name' =>'Chile (+56)');
$country_calling_codes['CN'] = array('value' =>'86', 'name' =>'China (+86)');
$country_calling_codes['CO'] = array('value' =>'57', 'name' =>'Colombia (+57)');
$country_calling_codes['KM'] = array('value' =>'269', 'name' =>'Comoros (+269)');
$country_calling_codes['CG'] = array('value' =>'242', 'name' =>'Congo (+242)');
$country_calling_codes['CK'] = array('value' =>'682', 'name' =>'Cook Islands (+682)');
$country_calling_codes['CR'] = array('value' =>'506', 'name' =>'Costa Rica (+506)');
$country_calling_codes['HR'] = array('value' =>'385', 'name' =>'Croatia (+385)');
$country_calling_codes['CU'] = array('value' =>'53', 'name' =>'Cuba (+53)');
$country_calling_codes['CY'] = array('value' =>'90', 'name' =>'Cyprus - North (+90)');
$country_calling_codes['CY'] = array('value' =>'357', 'name' =>'Cyprus - South (+357)');
$country_calling_codes['CZ'] = array('value' =>'420', 'name' =>'Czech Republic (+420)');
$country_calling_codes['DK'] = array('value' =>'45', 'name' =>'Denmark (+45)');
$country_calling_codes['DJ'] = array('value' =>'253', 'name' =>'Djibouti (+253)');
$country_calling_codes['DM'] = array('value' =>'1809', 'name' =>'Dominica (+1809)');
$country_calling_codes['DO'] = array('value' =>'1809', 'name' =>'Dominican Republic (+1809)');
$country_calling_codes['EC'] = array('value' =>'593', 'name' =>'Ecuador (+593)');
$country_calling_codes['EG'] = array('value' =>'20', 'name' =>'Egypt (+20)');
$country_calling_codes['SV'] = array('value' =>'503', 'name' =>'El Salvador (+503)');
$country_calling_codes['GQ'] = array('value' =>'240', 'name' =>'Equatorial Guinea (+240)');
$country_calling_codes['ER'] = array('value' =>'291', 'name' =>'Eritrea (+291)');
$country_calling_codes['EE'] = array('value' =>'372', 'name' =>'Estonia (+372)');
$country_calling_codes['ET'] = array('value' =>'251', 'name' =>'Ethiopia (+251)');
$country_calling_codes['FK'] = array('value' =>'500', 'name' =>'Falkland Islands (+500)');
$country_calling_codes['FO'] = array('value' =>'298', 'name' =>'Faroe Islands (+298)');
$country_calling_codes['FJ'] = array('value' =>'679', 'name' =>'Fiji (+679)');
$country_calling_codes['FI'] = array('value' =>'358', 'name' =>'Finland (+358)');
$country_calling_codes['FR'] = array('value' =>'33', 'name' =>'France (+33)');
$country_calling_codes['GF'] = array('value' =>'594', 'name' =>'French Guiana (+594)');
$country_calling_codes['PF'] = array('value' =>'689', 'name' =>'French Polynesia (+689)');
$country_calling_codes['GA'] = array('value' =>'241', 'name' =>'Gabon (+241)');
$country_calling_codes['GM'] = array('value' =>'220', 'name' =>'Gambia (+220)');
$country_calling_codes['GE'] = array('value' =>'7880', 'name' =>'Georgia (+7880)');
$country_calling_codes['DE'] = array('value' =>'49', 'name' =>'Germany (+49)');
$country_calling_codes['GH'] = array('value' =>'233', 'name' =>'Ghana (+233)');
$country_calling_codes['GI'] = array('value' =>'350', 'name' =>'Gibraltar (+350)');
$country_calling_codes['GR'] = array('value' =>'30', 'name' =>'Greece (+30)');
$country_calling_codes['GL'] = array('value' =>'299', 'name' =>'Greenland (+299)');
$country_calling_codes['GD'] = array('value' =>'1473', 'name' =>'Grenada (+1473)');
$country_calling_codes['GP'] = array('value' =>'590', 'name' =>'Guadeloupe (+590)');
$country_calling_codes['GU'] = array('value' =>'671', 'name' =>'Guam (+671)');
$country_calling_codes['GT'] = array('value' =>'502', 'name' =>'Guatemala (+502)');
$country_calling_codes['GN'] = array('value' =>'224', 'name' =>'Guinea (+224)');
$country_calling_codes['GW'] = array('value' =>'245', 'name' =>'Guinea - Bissau (+245)');
$country_calling_codes['GY'] = array('value' =>'592', 'name' =>'Guyana (+592)');
$country_calling_codes['HT'] = array('value' =>'509', 'name' =>'Haiti (+509)');
$country_calling_codes['HN'] = array('value' =>'504', 'name' =>'Honduras (+504)');
$country_calling_codes['HK'] = array('value' =>'852', 'name' =>'Hong Kong (+852)');
$country_calling_codes['HU'] = array('value' =>'36', 'name' =>'Hungary (+36)');
$country_calling_codes['IS'] = array('value' =>'354', 'name' =>'Iceland (+354)');
$country_calling_codes['IN'] = array('value' =>'91', 'name' =>'India (+91)');
$country_calling_codes['ID'] = array('value' =>'62', 'name' =>'Indonesia (+62)');
$country_calling_codes['IQ'] = array('value' =>'964', 'name' =>'Iraq (+964)');
$country_calling_codes['IR'] = array('value' =>'98', 'name' =>'Iran (+98)');
$country_calling_codes['IE'] = array('value' =>'353', 'name' =>'Ireland (+353)');
$country_calling_codes['IL'] = array('value' =>'972', 'name' =>'Israel (+972)');
$country_calling_codes['IT'] = array('value' =>'39', 'name' =>'Italy (+39)');
$country_calling_codes['JM'] = array('value' =>'1876', 'name' =>'Jamaica (+1876)');
$country_calling_codes['JP'] = array('value' =>'81', 'name' =>'Japan (+81)');
$country_calling_codes['JO'] = array('value' =>'962', 'name' =>'Jordan (+962)');
$country_calling_codes['KZ'] = array('value' =>'7', 'name' =>'Kazakhstan (+7)');
$country_calling_codes['KE'] = array('value' =>'254', 'name' =>'Kenya (+254)');
$country_calling_codes['KI'] = array('value' =>'686', 'name' =>'Kiribati (+686)');
$country_calling_codes['KP'] = array('value' =>'850', 'name' =>'Korea - North (+850)');
$country_calling_codes['KR'] = array('value' =>'82', 'name' =>'Korea - South (+82)');
$country_calling_codes['KW'] = array('value' =>'965', 'name' =>'Kuwait (+965)');
$country_calling_codes['KG'] = array('value' =>'996', 'name' =>'Kyrgyzstan (+996)');
$country_calling_codes['LA'] = array('value' =>'856', 'name' =>'Laos (+856)');
$country_calling_codes['LV'] = array('value' =>'371', 'name' =>'Latvia (+371)');
$country_calling_codes['LB'] = array('value' =>'961', 'name' =>'Lebanon (+961)');
$country_calling_codes['LS'] = array('value' =>'266', 'name' =>'Lesotho (+266)');
$country_calling_codes['LR'] = array('value' =>'231', 'name' =>'Liberia (+231)');
$country_calling_codes['LY'] = array('value' =>'218', 'name' =>'Libya (+218)');
$country_calling_codes['LI'] = array('value' =>'417', 'name' =>'Liechtenstein (+417)');
$country_calling_codes['LT'] = array('value' =>'370', 'name' =>'Lithuania (+370)');
$country_calling_codes['LU'] = array('value' =>'352', 'name' =>'Luxembourg (+352)');
$country_calling_codes['MO'] = array('value' =>'853', 'name' =>'Macao (+853)');
$country_calling_codes['MK'] = array('value' =>'389', 'name' =>'Macedonia (+389)');
$country_calling_codes['MG'] = array('value' =>'261', 'name' =>'Madagascar (+261)');
$country_calling_codes['MW'] = array('value' =>'265', 'name' =>'Malawi (+265)');
$country_calling_codes['MY'] = array('value' =>'60', 'name' =>'Malaysia (+60)');
$country_calling_codes['MV'] = array('value' =>'960', 'name' =>'Maldives (+960)');
$country_calling_codes['ML'] = array('value' =>'223', 'name' =>'Mali (+223)');
$country_calling_codes['MT'] = array('value' =>'356', 'name' =>'Malta (+356)');
$country_calling_codes['MH'] = array('value' =>'692', 'name' =>'Marshall Islands (+692)');
$country_calling_codes['MQ'] = array('value' =>'596', 'name' =>'Martinique (+596)');
$country_calling_codes['MR'] = array('value' =>'222', 'name' =>'Mauritania (+222)');
$country_calling_codes['YT'] = array('value' =>'269', 'name' =>'Mayotte (+269)');
$country_calling_codes['MX'] = array('value' =>'52', 'name' =>'Mexico (+52)');
$country_calling_codes['FM'] = array('value' =>'691', 'name' =>'Micronesia (+691)');
$country_calling_codes['MD'] = array('value' =>'373', 'name' =>'Moldova (+373)');
$country_calling_codes['MC'] = array('value' =>'377', 'name' =>'Monaco (+377)');
$country_calling_codes['MN'] = array('value' =>'976', 'name' =>'Mongolia (+976)');
$country_calling_codes['MS'] = array('value' =>'1664', 'name' =>'Montserrat (+1664)');
$country_calling_codes['MA'] = array('value' =>'212', 'name' =>'Morocco (+212)');
$country_calling_codes['MZ'] = array('value' =>'258', 'name' =>'Mozambique (+258)');
$country_calling_codes['MN'] = array('value' =>'95', 'name' =>'Myanmar (+95)');
$country_calling_codes['NA'] = array('value' =>'264', 'name' =>'Namibia (+264)');
$country_calling_codes['NR'] = array('value' =>'674', 'name' =>'Nauru (+674)');
$country_calling_codes['NP'] = array('value' =>'977', 'name' =>'Nepal (+977)');
$country_calling_codes['NL'] = array('value' =>'31', 'name' =>'Netherlands (+31)');
$country_calling_codes['NC'] = array('value' =>'687', 'name' =>'New Caledonia (+687)');
$country_calling_codes['NZ'] = array('value' =>'64', 'name' =>'New Zealand (+64)');
$country_calling_codes['NI'] = array('value' =>'505', 'name' =>'Nicaragua (+505)');
$country_calling_codes['NE'] = array('value' =>'227', 'name' =>'Niger (+227)');
$country_calling_codes['NG'] = array('value' =>'234', 'name' =>'Nigeria (+234)');
$country_calling_codes['NU'] = array('value' =>'683', 'name' =>'Niue (+683)');
$country_calling_codes['NF'] = array('value' =>'672', 'name' =>'Norfolk Islands (+672)');
$country_calling_codes['NP'] = array('value' =>'670', 'name' =>'Northern Marianas (+670)');
$country_calling_codes['NO'] = array('value' =>'47', 'name' =>'Norway (+47)');
$country_calling_codes['OM'] = array('value' =>'968', 'name' =>'Oman (+968)');
$country_calling_codes['PK'] = array('value' =>'92', 'name' =>'Pakistan (+92)');
$country_calling_codes['PW'] = array('value' =>'680', 'name' =>'Palau (+680)');
$country_calling_codes['PA'] = array('value' =>'507', 'name' =>'Panama (+507)');
$country_calling_codes['PG'] = array('value' =>'675', 'name' =>'Papua New Guinea (+675)');
$country_calling_codes['PY'] = array('value' =>'595', 'name' =>'Paraguay (+595)');
$country_calling_codes['PE'] = array('value' =>'51', 'name' =>'Peru (+51)');
$country_calling_codes['PH'] = array('value' =>'63', 'name' =>'Philippines (+63)');
$country_calling_codes['PL'] = array('value' =>'48', 'name' =>'Poland (+48)');
$country_calling_codes['PT'] = array('value' =>'351', 'name' =>'Portugal (+351)');
$country_calling_codes['PR'] = array('value' =>'1787', 'name' =>'Puerto Rico (+1787)');
$country_calling_codes['QA'] = array('value' =>'974', 'name' =>'Qatar (+974)');
$country_calling_codes['RE'] = array('value' =>'262', 'name' =>'Reunion (+262)');
$country_calling_codes['RO'] = array('value' =>'40', 'name' =>'Romania (+40)');
$country_calling_codes['RU'] = array('value' =>'7', 'name' =>'Russia (+7)');
$country_calling_codes['RW'] = array('value' =>'250', 'name' =>'Rwanda (+250)');
$country_calling_codes['SM'] = array('value' =>'378', 'name' =>'San Marino (+378)');
$country_calling_codes['ST'] = array('value' =>'239', 'name' =>'Sao Tome &amp; Principe (+239)');
$country_calling_codes['SA'] = array('value' =>'966', 'name' =>'Saudi Arabia (+966)');
$country_calling_codes['SN'] = array('value' =>'221', 'name' =>'Senegal (+221)');
$country_calling_codes['CS'] = array('value' =>'381', 'name' =>'Serbia (+381)');
$country_calling_codes['SC'] = array('value' =>'248', 'name' =>'Seychelles (+248)');
$country_calling_codes['SL'] = array('value' =>'232', 'name' =>'Sierra Leone (+232)');
$country_calling_codes['SG'] = array('value' =>'65', 'name' =>'Singapore (+65)');
$country_calling_codes['SK'] = array('value' =>'421', 'name' =>'Slovak Republic (+421)');
$country_calling_codes['SI'] = array('value' =>'386', 'name' =>'Slovenia (+386)');
$country_calling_codes['SB'] = array('value' =>'677', 'name' =>'Solomon Islands (+677)');
$country_calling_codes['SO'] = array('value' =>'252', 'name' =>'Somalia (+252)');
$country_calling_codes['ZA'] = array('value' =>'27', 'name' =>'South Africa (+27)');
$country_calling_codes['ES'] = array('value' =>'34', 'name' =>'Spain (+34)');
$country_calling_codes['LK'] = array('value' =>'94', 'name' =>'Sri Lanka (+94)');
$country_calling_codes['SH'] = array('value' =>'290', 'name' =>'St. Helena (+290)');
$country_calling_codes['KN'] = array('value' =>'1869', 'name' =>'St. Kitts (+1869)');
$country_calling_codes['SC'] = array('value' =>'1758', 'name' =>'St. Lucia (+1758)');
$country_calling_codes['SR'] = array('value' =>'597', 'name' =>'Suriname (+597)');
$country_calling_codes['SD'] = array('value' =>'249', 'name' =>'Sudan (+249)');
$country_calling_codes['SZ'] = array('value' =>'268', 'name' =>'Swaziland (+268)');
$country_calling_codes['SE'] = array('value' =>'46', 'name' =>'Sweden (+46)');
$country_calling_codes['CH'] = array('value' =>'41', 'name' =>'Switzerland (+41)');
$country_calling_codes['SY'] = array('value' =>'963', 'name' =>'Syria (+963)');
$country_calling_codes['TW'] = array('value' =>'886', 'name' =>'Taiwan (+886)');
$country_calling_codes['TJ'] = array('value' =>'992', 'name' =>'Tajikistan (+992)');
$country_calling_codes['TH'] = array('value' =>'66', 'name' =>'Thailand (+66)');
$country_calling_codes['TG'] = array('value' =>'228', 'name' =>'Togo (+228)');
$country_calling_codes['TO'] = array('value' =>'676', 'name' =>'Tonga (+676)');
$country_calling_codes['TT'] = array('value' =>'1868', 'name' =>'Trinidad &amp; Tobago (+1868)');
$country_calling_codes['TN'] = array('value' =>'216', 'name' =>'Tunisia (+216)');
$country_calling_codes['TR'] = array('value' =>'90', 'name' =>'Turkey (+90)');
$country_calling_codes['TM'] = array('value' =>'993', 'name' =>'Turkmenistan (+993)');
$country_calling_codes['TC'] = array('value' =>'1649', 'name' =>'Turks &amp; Caicos Islands (+1649)');
$country_calling_codes['TV'] = array('value' =>'688', 'name' =>'Tuvalu (+688)');
$country_calling_codes['UG'] = array('value' =>'256', 'name' =>'Uganda (+256)');
$country_calling_codes['GB'] = array('value' =>'44', 'name' =>'UK (+44)');
$country_calling_codes['UA'] = array('value' =>'380', 'name' =>'Ukraine (+380)');
$country_calling_codes['AE'] = array('value' =>'971', 'name' =>'United Arab Emirates (+971)');
$country_calling_codes['UY'] = array('value' =>'598', 'name' =>'Uruguay (+598)');
$country_calling_codes['US'] = array('value' =>'1', 'name' =>'USA (+1)');
$country_calling_codes['UZ'] = array('value' =>'998', 'name' =>'Uzbekistan (+998)');
$country_calling_codes['VU'] = array('value' =>'678', 'name' =>'Vanuatu (+678)');
$country_calling_codes['VA'] = array('value' =>'379', 'name' =>'Vatican City (+379)');
$country_calling_codes['VE'] = array('value' =>'58', 'name' =>'Venezuela (+58)');
$country_calling_codes['VN'] = array('value' =>'84', 'name' =>'Vietnam (+84)');
$country_calling_codes['WF'] = array('value' =>'681', 'name' =>'Wallis &amp; Futuna (+681)');
$country_calling_codes['YE'] = array('value' =>'969', 'name' =>'Yemen (North)(+969)');
$country_calling_codes['YE'] = array('value' =>'967', 'name' =>'Yemen (South)(+967)');
$country_calling_codes['ZM'] = array('value' =>'260', 'name' =>'Zambia (+260)');
$country_calling_codes['ZW'] = array('value' =>'263', 'name' =>'Zimbabwe (+263)');
