SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `reviews` ADD FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `rel_place_cat` ADD `is_main` INT(1) NOT NULL DEFAULT '1' AFTER `city_id`;
SET FOREIGN_KEY_CHECKS=1;