SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: `directoryplus`
--

--
-- Table structure change for table `places`
--

ALTER TABLE `places` ADD `country_code` VARCHAR(10) NOT NULL DEFAULT '' AFTER `state_id`;

ALTER TABLE `places` ADD `wa_country_code` VARCHAR(10) NOT NULL DEFAULT '' AFTER `phone`, ADD `wa_area_code` VARCHAR(10) NOT NULL DEFAULT '' AFTER `wa_country_code`, ADD `wa_phone` VARCHAR(50) NOT NULL DEFAULT '' AFTER `wa_area_code`;

ALTER TABLE `places` CHANGE `specialties` `short_desc` VARCHAR(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '';

--
-- Backup old `transactions` table
--

RENAME TABLE `transactions` TO `transactions_old`;

--
-- Create new `transactions` table
--

CREATE TABLE IF NOT EXISTS `transactions` (
  `id` int(11) NOT NULL,
  `txn_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `place_id` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `user` int(11) NOT NULL,
  `paym_email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `gateway` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `amount` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `txn_data` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `txn_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Indexes for table `transactions`
--
ALTER TABLE `transactions`
  ADD PRIMARY KEY (`id`),
  ADD KEY `place_id` (`place_id`),
  ADD KEY `user` (`user`);

--
-- AUTO_INCREMENT for table `transactions`
--
ALTER TABLE `transactions`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- Table change for table `email_templates`
--

ALTER TABLE `email_templates` ADD `available_vars` TEXT NOT NULL AFTER `body`;

INSERT INTO `email_templates` (`type`, `description`, `subject`, `body`, `available_vars`) VALUES ('charge_failed', 'Email sent when a payment failed', 'Charge failed', 'Hello,\n\nYour recent payment did not complete and credits were not added to the database. Please contact the site administrator.\n\nThanks,\n%site_name% - %site_url%', '%site_name%\n%site_url%');
INSERT INTO `email_templates` (`type`, `description`, `subject`, `body`, `available_vars`) VALUES ('user_signup', 'Email sent to the admin when a new user registers on the site', 'New User Signup', 'New signup from user: \n%signup_email%', '%signup_email%');

UPDATE `email_templates` SET `type` = 'process_add_listing' WHERE `type` = 'process_add_place';
UPDATE `email_templates` SET `type` = 'process_edit_listing' WHERE `type` = 'process_edit_place';

UPDATE `email_templates` SET `available_vars` = '%site_name%\n%site_url%\n%reset_link%' WHERE `type` = 'reset_pass';
UPDATE `email_templates` SET `available_vars` = '%site_name%\n%site_url%\n%confirm_link%' WHERE `type` = 'signup_confirm';
UPDATE `email_templates` SET `available_vars` = '%site_name%\n%site_url%' WHERE `type` IN('subscr_failed','subscr_signup','web_accept','subscr_eot','charge_failed','web_accept_fail');
UPDATE `email_templates` SET `available_vars` = '%new_listing_url%' WHERE  `type` = 'process_add_listing';
UPDATE `email_templates` SET `available_vars` = '%edited_listing_url%' WHERE  `type` = 'process_edit_listing';
UPDATE `email_templates` SET `body` = 'A user has edited a listing at:\n%edited_listing_url% ' WHERE `type` = 'process_edit_listing';

--
-- Table structure for table `language`
--

CREATE TABLE IF NOT EXISTS `language` (
  `id` int(11) NOT NULL,
  `lang` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'en',
  `section` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'public',
  `template` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `var_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `translated` text COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `language`
  ADD PRIMARY KEY (`id`),
  ADD KEY `lang` (`lang`),
  ADD KEY `template` (`template`),
  ADD KEY `section` (`section`);


ALTER TABLE `language`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

DELETE FROM `language` WHERE lang='en';

INSERT INTO `language` (`lang`, `section`, `template`, `var_name`, `translated`) VALUES
('en', 'public', 'global', 'txt_admin', 'Admin Area'),
('en', 'public', 'global', 'txt_address', 'Address'),
('en', 'public', 'global', 'txt_approve', 'Approve'),
('en', 'public', 'global', 'txt_approved', 'Approved'),
('en', 'public', 'global', 'txt_asearch', 'Advanced Search'),
('en', 'public', 'global', 'txt_bg_color', 'Background color'),
('en', 'public', 'global', 'txt_blog', 'Blog'),
('en', 'public', 'global', 'txt_cancel', 'Cancel'),
('en', 'public', 'global', 'txt_category', 'Category'),
('en', 'public', 'global', 'txt_categories', 'Categories'),
('en', 'public', 'global', 'txt_change', 'Change'),
('en', 'public', 'global', 'txt_change_pass', 'Change Password'),
('en', 'public', 'global', 'txt_cities', 'Cities'),
('en', 'public', 'global', 'txt_city', 'City'),
('en', 'public', 'global', 'txt_clear', 'Clear'),
('en', 'public', 'global', 'txt_close', 'Close'),
('en', 'public', 'global', 'txt_confirm', 'Confirm'),
('en', 'public', 'global', 'txt_contact', 'Contact'),
('en', 'public', 'global', 'txt_contact_user', 'Contact User'),
('en', 'public', 'global', 'txt_countries', 'Countries'),
('en', 'public', 'global', 'txt_country', 'Country'),
('en', 'public', 'global', 'txt_coupon', 'Coupon'),
('en', 'public', 'global', 'txt_coupons', 'Coupons'),
('en', 'public', 'global', 'txt_create_listing', 'Create Listing'),
('en', 'public', 'global', 'txt_dashboard', 'Dashboard'),
('en', 'public', 'global', 'txt_date', 'Date'),
('en', 'public', 'global', 'txt_delete', 'Delete'),
('en', 'public', 'global', 'txt_disabled', 'Disabled'),
('en', 'public', 'global', 'txt_email', 'Email'),
('en', 'public', 'global', 'txt_enabled', 'Enabled'),
('en', 'public', 'global', 'txt_event', 'Event'),
('en', 'public', 'global', 'txt_events', 'Events'),
('en', 'public', 'global', 'txt_execute', 'Execute'),
('en', 'public', 'global', 'txt_explore', 'Explore'),
('en', 'public', 'global', 'txt_favorites', 'Favorites'),
('en', 'public', 'global', 'txt_featured', 'Featured'),
('en', 'public', 'global', 'txt_get_listed', 'Get Listed Today'),
('en', 'public', 'global', 'txt_help', 'Help'),
('en', 'public', 'global', 'txt_home', 'Home'),
('en', 'public', 'global', 'txt_id', 'Id'),
('en', 'public', 'global', 'txt_invalid_email', 'Invalid email'),
('en', 'public', 'global', 'txt_keyword', 'Ex: pizza, hotel, car sale'),
('en', 'public', 'global', 'txt_listing', 'Listing'),
('en', 'public', 'global', 'txt_listings', 'Listings'),
('en', 'public', 'global', 'txt_loading', 'Loading'),
('en', 'public', 'global', 'txt_location', 'Location'),
('en', 'public', 'global', 'txt_manager', 'Manager'),
('en', 'public', 'global', 'txt_message', 'Message'),
('en', 'public', 'global', 'txt_message_sent', 'Message sent'),
('en', 'public', 'global', 'txt_meta_desc', ''),
('en', 'public', 'global', 'txt_month', 'Month'),
('en', 'public', 'global', 'txt_name', 'Name'),
('en', 'public', 'global', 'txt_no', 'No'),
('en', 'public', 'global', 'txt_no_results', 'No results'),
('en', 'public', 'global', 'txt_ok', 'OK'),
('en', 'public', 'global', 'txt_optional', 'Optional'),
('en', 'public', 'global', 'txt_page', 'Page'),
('en', 'public', 'global', 'txt_pager_page1', 'Page 1'),
('en', 'public', 'global', 'txt_pager_last_page', 'Last Page'),
('en', 'public', 'global', 'txt_pages', 'Pages'),
('en', 'public', 'global', 'txt_password', 'Password'),
('en', 'public', 'global', 'txt_pending', 'Pending'),
('en', 'public', 'global', 'txt_phone', 'Phone'),
('en', 'public', 'global', 'txt_photo', 'Photo'),
('en', 'public', 'global', 'txt_photos', 'Photos'),
('en', 'public', 'global', 'txt_picture', 'Picture'),
('en', 'public', 'global', 'txt_pictures', 'Pictures'),
('en', 'public', 'global', 'txt_postal_code', 'Postal Code'),
('en', 'public', 'global', 'txt_print', 'Print'),
('en', 'public', 'global', 'txt_privacy_agree', 'I agree to the terms of use and privacy policy'),
('en', 'public', 'global', 'txt_profile', 'Profile'),
('en', 'public', 'global', 'txt_rate_bad', 'bad'),
('en', 'public', 'global', 'txt_rate_good', 'good'),
('en', 'public', 'global', 'txt_rate_gorgeous', 'gorgeous'),
('en', 'public', 'global', 'txt_rate_poor', 'poor'),
('en', 'public', 'global', 'txt_rate_regular', 'regular'),
('en', 'public', 'global', 'txt_register', 'Register'),
('en', 'public', 'global', 'txt_remaining', 'Remaining'),
('en', 'public', 'global', 'txt_remove', 'Remove'),
('en', 'public', 'global', 'txt_required', 'Required'),
('en', 'public', 'global', 'txt_reviews', 'Reviews'),
('en', 'public', 'global', 'txt_save', 'Save changes'),
('en', 'public', 'global', 'txt_search', 'Search'),
('en', 'public', 'global', 'txt_selectyourcity', 'Select city'),
('en', 'public', 'global', 'txt_send_message', 'Send Message'),
('en', 'public', 'global', 'txt_short_desc', 'Short Description'),
('en', 'public', 'global', 'txt_signin', 'Sign in'),
('en', 'public', 'global', 'txt_signout', 'Sign out'),
('en', 'public', 'global', 'txt_state', 'State'),
('en', 'public', 'global', 'txt_states', 'States'),
('en', 'public', 'global', 'txt_subject', 'Subject'),
('en', 'public', 'global', 'txt_submit', 'Submit'),
('en', 'public', 'global', 'txt_sort', 'Sort'),
('en', 'public', 'global', 'txt_tags', 'Tags'),
('en', 'public', 'global', 'txt_thanks', 'Thanks'),
('en', 'public', 'global', 'txt_total_rows', 'Total rows'),
('en', 'public', 'global', 'txt_try_again', 'Try again'),
('en', 'public', 'global', 'txt_upload', 'Upload'),
('en', 'public', 'global', 'txt_upload_limit', 'Upload Limit Reached'),
('en', 'public', 'global', 'txt_use_cur_loc', 'Use current location'),
('en', 'public', 'global', 'txt_user', 'User'),
('en', 'public', 'global', 'txt_video', 'Video'),
('en', 'public', 'global', 'txt_videos', 'Videos'),
('en', 'public', 'global', 'txt_users', 'Users'),
('en', 'public', 'global', 'txt_view_all', 'View All'),
('en', 'public', 'global', 'txt_wait', 'Wait'),
('en', 'public', 'global', 'txt_year', 'Year'),
('en', 'public', 'global', 'txt_yes', 'Yes'),
('en', 'public', 'home', 'txt_html_title', 'Business Directory'),
('en', 'public', 'home', 'txt_meta_desc', 'Business Directory is a nationwide business directory where users can search for the businesses near them and write reviews.'),
('en', 'public', 'home', 'txt_featured_cities', 'Featured Cities'),
('en', 'public', 'home', 'txt_featured_listings', 'Featured Listings'),
('en', 'public', 'home', 'txt_latest_listings', 'Latest Listings'),
('en', 'public', 'home', 'txt_near_listings', 'Places Near You'),
('en', 'public', 'home', 'txt_view_cat', 'View Category'),
('en', 'public', 'home', 'txt_view_listing', 'View Listing'),
('en', 'public', 'home', 'txt_view_listings', 'View Listings'),
('en', 'public', 'home', 'txt_phrase_01', 'Explore places in this city'),
('en', 'public', 'home', 'txt_phrase_02', 'Find the best hotels, shops and restaurants in your local area.'),
('en', 'public', 'home', 'txt_phrase_03', 'Most Popular Categories'),
('en', 'public', 'home', 'txt_phrase_04', 'Featured Listings'),
('en', 'public', 'home', 'txt_phrase_05', 'Explore The Latest Listings'),
('en', 'public', 'home', 'txt_phrase_06', 'Most Popular Cities'),
('en', 'public', 'home', 'txt_phrase_07', 'Recommended Places Near You'),
('en', 'public', 'home', 'txt_phrase_08', ''),
('en', 'public', 'home', 'txt_phrase_09', ''),
('en', 'public', 'home', 'txt_phrase_10', ''),
('en', 'public', 'categories', 'txt_html_title_1', 'All Categories in %city_name%, %state_abbr%'),
('en', 'public', 'categories', 'txt_meta_desc_1', 'Best businesses in %city_name%, %state_abbr%'),
('en', 'public', 'categories', 'txt_main_title_1', 'All Categories in %city_name%, %state_abbr%'),
('en', 'public', 'categories', 'txt_suggest_city', 'Show categories in %city_name%'),
('en', 'public', 'categories', 'txt_all_cats_city', 'All Categories in %city_name%'),
('en', 'public', 'categories', 'txt_all_locs', 'All locations'),
('en', 'public', 'categories', 'txt_html_title_2', 'All Categories'),
('en', 'public', 'categories', 'txt_meta_desc_2', 'Best businesses'),
('en', 'public', 'categories', 'txt_main_title_2', 'All Categories'),
('en', 'public', 'categories', 'txt_all_cats', 'All Categories'),
('en', 'public', 'claim', 'txt_html_title', 'Claim Listing'),
('en', 'public', 'claim', 'txt_main_title', 'Claim Listing'),
('en', 'public', 'claim', 'txt_buy_now', 'Select this plan'),
('en', 'public', 'claim', 'txt_claimed', 'This place has already been claimed'),
('en', 'public', 'claim', 'txt_month', 'month'),
('en', 'public', 'claim', 'txt_no_plans', 'There are no plans defined.'),
('en', 'public', 'claim', 'txt_sign_in', 'To claim this listing you need to sign in.'),
('en', 'public', 'claim', 'txt_year', 'year'),
('en', 'public', 'claim', 'txt_select_plan', 'Select Plan'),
('en', 'public', 'contact', 'txt_html_title', 'Contact'),
('en', 'public', 'contact', 'txt_main_title', 'Contact'),
('en', 'public', 'contact', 'txt_message', 'Message'),
('en', 'public', 'contact', 'txt_send_message', 'Send Message'),
('en', 'public', 'contact', 'txt_message_sent', 'Message sent.'),
('en', 'public', 'coupon', 'txt_html_title', 'Coupons'),
('en', 'public', 'coupon', 'txt_meta_desc', 'Coupons'),
('en', 'public', 'coupon', 'txt_view_details', 'View Details'),
('en', 'public', 'coupon', 'txt_tweet', 'Tweet'),
('en', 'public', 'coupon', 'txt_share', 'Share'),
('en', 'public', 'coupon', 'txt_mail', 'Mail'),
('en', 'public', 'coupon', 'txt_created_by', 'Created by'),
('en', 'public', 'coupon', 'txt_expires', 'Expires'),
('en', 'public', 'coupon', 'txt_expired', 'Expired'),
('en', 'public', 'coupon', 'txt_about_coupon', 'About this coupon'),
('en', 'public', 'coupons', 'txt_html_title', 'Coupons'),
('en', 'public', 'coupons', 'txt_meta_desc', 'Coupons'),
('en', 'public', 'coupons', 'txt_view_details', 'View Details'),
('en', 'public', 'coupons', 'txt_tweet', 'Tweet'),
('en', 'public', 'coupons', 'txt_share', 'Share'),
('en', 'public', 'coupons', 'txt_mail', 'Mail'),
('en', 'public', 'coupons', 'txt_created_by', 'Created by'),
('en', 'public', 'coupons', 'txt_expires', 'Expires'),
('en', 'public', 'coupons', 'txt_expired', 'Expired'),
('en', 'public', 'coupons', 'txt_about_coupon', 'About this coupon'),
('en', 'public', 'favorites', 'txt_html_title', '%profile_display_name%''s Favorites'),
('en', 'public', 'favorites', 'txt_meta_desc', '%profile_display_name%''s Favorites'),
('en', 'public', 'favorites', 'txt_joined_on', 'Joined on %join_date%'),
('en', 'public', 'listing', 'txt_add_to_favorites', 'Add to Favorites'),
('en', 'public', 'listing', 'txt_additional_info', 'Additional Info'),
('en', 'public', 'listing', 'txt_claim', 'Claim Listing'),
('en', 'public', 'listing', 'txt_click_to_chat', 'Click to chat using whatsapp'),
('en', 'public', 'listing', 'txt_contact_business', 'Send Message'),
('en', 'public', 'listing', 'txt_description', 'Description'),
('en', 'public', 'listing', 'txt_features', 'Features'),
('en', 'public', 'listing', 'txt_hours', 'Hours'),
('en', 'public', 'listing', 'txt_location', 'Location'),
('en', 'public', 'listing', 'txt_more_details', 'More Details'),
('en', 'public', 'listing', 'txt_other_places', 'Other places'),
('en', 'public', 'listing', 'txt_overview', 'Overview'),
('en', 'public', 'listing', 'txt_please_rate', 'Please rate this business'),
('en', 'public', 'listing', 'txt_please_wait', 'Please wait a few seconds before submitting again'),
('en', 'public', 'listing', 'txt_related', 'See Also'),
('en', 'public', 'listing', 'txt_review_login_req', 'To write a review, you must login first.'),
('en', 'public', 'listing', 'txt_review_txtarea_label', 'Review'),
('en', 'public', 'listing', 'txt_send_email', 'Send an email'),
('en', 'public', 'listing', 'txt_share', 'Share This Place'),
('en', 'public', 'listing', 'txt_similar_listings', 'Similar Items'),
('en', 'public', 'listing', 'txt_social', 'Social Media'),
('en', 'public', 'listing', 'txt_short_desc', 'Short Description'),
('en', 'public', 'listing', 'txt_view_details', 'View Details'),
('en', 'public', 'listing', 'txt_website', 'Website'),
('en', 'public', 'listing', 'txt_write_review', 'Write a review'),
('en', 'public', 'listing', 'txt_your_email', 'Your email'),
('en', 'public', 'listings', 'txt_html_title', 'Best %plural_name% in %location%'),
('en', 'public', 'listings', 'txt_meta_desc', 'Best %plural_name% in %location%. %places_names% and others.'),
('en', 'public', 'listings', 'txt_businesses', 'Businesses'),
('en', 'public', 'listings', 'txt_no_results', 'There are no listings to display.'),
('en', 'public', 'listings', 'txt_pager_lastpage', 'Last Page'),
('en', 'public', 'listings', 'txt_pager_page1', 'Page 1'),
('en', 'public', 'listings', 'txt_recommended', 'Recommended'),
('en', 'public', 'listings', 'txt_results', 'Result(s)'),
('en', 'public', 'msg', 'txt_main_title_stripe', 'Thank you for your payment'),
('en', 'public', 'msg', 'txt_msg_stripe', 'Payment successful. Thank you for your business!'),
('en', 'public', 'post', 'txt_view_details', 'View Details'),
('en', 'public', 'post', 'txt_tweet', 'Tweet'),
('en', 'public', 'post', 'txt_share', 'Share'),
('en', 'public', 'post', 'txt_mail', 'Mail'),
('en', 'public', 'post', 'txt_created_by', 'Created by'),
('en', 'public', 'post', 'txt_expires', 'Expires'),
('en', 'public', 'post', 'txt_expired', 'Expired'),
('en', 'public', 'post', 'txt_about_coupon', 'About this coupon'),
('en', 'public', 'post', 'txt_search_pages', 'Search blog'),
('en', 'public', 'posts', 'txt_html_title', 'Website Blog'),
('en', 'public', 'posts', 'txt_meta_desc', 'Website Blog'),
('en', 'public', 'posts', 'txt_view_details', 'View Details'),
('en', 'public', 'posts', 'txt_tweet', 'Tweet'),
('en', 'public', 'posts', 'txt_share', 'Share'),
('en', 'public', 'posts', 'txt_mail', 'Mail'),
('en', 'public', 'posts', 'txt_search_pages', 'Search blog'),
('en', 'public', 'posts', 'txt_posted_on', 'Posted on %date%'),
('en', 'public', 'profile', 'txt_html_title', '%profile_display_name% Profile'),
('en', 'public', 'profile', 'txt_meta_desc', '%profile_display_name% Profile'),
('en', 'public', 'profile', 'txt_joined_on', 'Joined on %join_date%'),
('en', 'public', 'profile', 'txt_recent_activity', 'Recent Activity'),
('en', 'public', 'profile', 'txt_no_activity', 'No recent activity'),
('en', 'public', 'reviews', 'txt_html_title', '%profile_display_name%''s Reviews'),
('en', 'public', 'reviews', 'txt_meta_desc', '%profile_display_name%''s Reviews'),
('en', 'public', 'reviews', 'txt_joined_on', 'Joined on %join_date%'),
('en', 'user', 'create-listing', 'txt_html_title', 'Create Listing'),
('en', 'user', 'create-listing', 'txt_main_title', 'Create Listing'),
('en', 'user', 'create-listing', 'txt_meta_desc', ''),
('en', 'user', 'create-listing', 'txt_area_code', 'Area Code'),
('en', 'user', 'create-listing', 'txt_business_name', 'Business Name'),
('en', 'user', 'create-listing', 'txt_click_map', 'Please click on the map to create a marker representing the business location.'),
('en', 'user', 'create-listing', 'txt_cross_street', 'Cross street'),
('en', 'user', 'create-listing', 'txt_custom_fields', 'Custom fields'),
('en', 'user', 'create-listing', 'txt_description', 'Description'),
('en', 'user', 'create-listing', 'txt_error_file_size', 'The uploaded file exceeds allowed size'),
('en', 'user', 'create-listing', 'txt_error_upload', 'Problem uploading file. Please try again or try another file.'),
('en', 'user', 'create-listing', 'txt_hours', 'Hours'),
('en', 'user', 'create-listing', 'txt_logo', 'Logo'),
('en', 'user', 'create-listing', 'txt_neighborhood', 'Neighborhood'),
('en', 'user', 'create-listing', 'txt_other_info', 'Other Information'),
('en', 'user', 'create-listing', 'txt_postal_code', 'Postal Code'),
('en', 'user', 'create-listing', 'txt_select_cat', 'Select category'),
('en', 'user', 'create-listing', 'txt_select_city', 'Select city'),
('en', 'user', 'create-listing', 'txt_submit_listing', 'Submit Listing'),
('en', 'user', 'create-listing', 'txt_upload', 'Upload photos'),
('en', 'user', 'create-listing', 'txt_upload_btn', 'Browse'),
('en', 'user', 'create-listing', 'txt_upload_logo', 'Upload logo'),
('en', 'user', 'create-listing', 'txt_validate_addr', 'Please enter the address'),
('en', 'user', 'create-listing', 'txt_validate_cat', 'Please select a category'),
('en', 'user', 'create-listing', 'txt_validate_city', 'Please select a city'),
('en', 'user', 'create-listing', 'txt_validate_map', 'Please place a pin on the map'),
('en', 'user', 'create-listing', 'txt_validate_name', 'Please enter the business name'),
('en', 'user', 'create-listing', 'txt_website', 'Website'),
('en', 'user', 'edit-listing', 'txt_html_title', 'Edit Business Information'),
('en', 'user', 'edit-listing', 'txt_main_title', 'Edit Business Information'),
('en', 'user', 'edit-listing', 'txt_sub_header', 'Editing information for: %place_name%'),
('en', 'user', 'edit-listing', 'txt_area_code', 'Area Code'),
('en', 'user', 'edit-listing', 'txt_business_info', 'Business Information'),
('en', 'user', 'edit-listing', 'txt_business_name', 'Business Name'),
('en', 'user', 'edit-listing', 'txt_click_map', 'Please click on the map to create a marker representing the business location.'),
('en', 'user', 'edit-listing', 'txt_cross_street', 'Cross street'),
('en', 'user', 'edit-listing', 'txt_custom_fields', 'Custom fields'),
('en', 'user', 'edit-listing', 'txt_description', 'Description'),
('en', 'user', 'edit-listing', 'txt_error_file_size', 'The uploaded file exceeds allowed size'),
('en', 'user', 'edit-listing', 'txt_error_upload', 'Problem uploading file. Please try again or try another file.'),
('en', 'user', 'edit-listing', 'txt_hours', 'Hours'),
('en', 'user', 'edit-listing', 'txt_neighborhood', 'Neighborhood'),
('en', 'user', 'edit-listing', 'txt_logo', 'Logo'),
('en', 'user', 'edit-listing', 'txt_other_info', 'Other Information'),
('en', 'user', 'edit-listing', 'txt_postal_code', 'Postal Code'),
('en', 'user', 'edit-listing', 'txt_select_cat', 'Select category'),
('en', 'user', 'edit-listing', 'txt_select_city', 'Select city'),
('en', 'user', 'edit-listing', 'txt_submit_listing', 'Submit Listing'),
('en', 'user', 'edit-listing', 'txt_upload', 'Upload photos'),
('en', 'user', 'edit-listing', 'txt_upload_btn', 'Browse'),
('en', 'user', 'edit-listing', 'txt_upload_logo', 'Upload logo'),
('en', 'user', 'edit-listing', 'txt_validate_addr', 'Please enter the address'),
('en', 'user', 'edit-listing', 'txt_validate_cat', 'Please select a category'),
('en', 'user', 'edit-listing', 'txt_validate_city', 'Please select a city'),
('en', 'user', 'edit-listing', 'txt_validate_map', 'Please place a pin on the map'),
('en', 'user', 'edit-listing', 'txt_validate_name', 'Please enter the business name'),
('en', 'user', 'edit-listing', 'txt_website', 'Website'),
('en', 'user', 'edit-pass', 'txt_html_title', 'Edit Pass'),
('en', 'user', 'edit-pass', 'txt_main_title', 'Change Password'),
('en', 'user', 'edit-pass', 'txt_label_cur_pass', 'Current Password'),
('en', 'user', 'edit-pass', 'txt_label_new_pass', 'New Password'),
('en', 'user', 'edit-pass', 'txt_btn_submit', 'Save Changes'),
('en', 'user', 'edit-pass', 'txt_social_user', '<p>You''re logged in using Facebook or Twitter, so you don''t have to manage a password for this site.</p>'),
('en', 'user', 'forgot-password', 'txt_html_title', 'Forgot your password'),
('en', 'user', 'forgot-password', 'txt_main_title', 'Forgot your password?'),
('en', 'user', 'forgot-password', 'txt_forgot_pass', 'Forgot password'),
('en', 'user', 'forgot-password', 'txt_enter_email', 'Enter your email address to reset your password'),
('en', 'user', 'forgot-password', 'txt_or_login', 'Or'),
('en', 'user', 'forgot-password', 'txt_request_sent', 'You will receive a password recovery link at your email address in a few seconds.'),
('en', 'user', 'forgot-password', 'txt_mailer_problem', 'Error: could not deliver email to the specified address. Please try again.'),
('en', 'user', 'forgot-password', 'txt_invalid_email', 'Invalid email address. Please try again.'),
('en', 'user', 'forgot-password', 'txt_try_again', 'Try again'),
('en', 'user', 'my-coupons', 'txt_html_title', 'My Coupons'),
('en', 'user', 'my-coupons', 'txt_main_title', 'My Coupons'),
('en', 'user', 'my-coupons', 'txt_no_coupons', 'You haven''t created any coupons yet.'),
('en', 'user', 'my-coupons', 'txt_no_listings', 'To create coupons, please create a listing first.'),
('en', 'user', 'my-coupons', 'txt_title', 'Title'),
('en', 'user', 'my-coupons', 'txt_description', 'Coupon description'),
('en', 'user', 'my-coupons', 'txt_expire', 'Valid until'),
('en', 'user', 'my-coupons', 'txt_expired', 'Expired'),
('en', 'user', 'my-coupons', 'txt_apply_to', 'Apply to'),
('en', 'user', 'my-coupons', 'txt_img', 'Coupon image'),
('en', 'user', 'my-coupons', 'txt_create', 'Create coupon'),
('en', 'user', 'my-coupons', 'txt_remove_warn', 'Are you sure you want to delete this coupon?'),
('en', 'user', 'my-favorites', 'txt_html_title', 'My Favorites'),
('en', 'user', 'my-favorites', 'txt_main_title', 'My Favorites'),
('en', 'user', 'my-listings', 'txt_html_title', 'My Listings'),
('en', 'user', 'my-listings', 'txt_main_title', 'My Listings'),
('en', 'user', 'my-listings', 'txt_remove_place', 'Remove Listing'),
('en', 'user', 'my-listings', 'txt_edit_place', 'Edit Listing'),
('en', 'user', 'my-listings', 'txt_status_approved', 'Approved'),
('en', 'user', 'my-listings', 'txt_status_pending', 'Pending'),
('en', 'user', 'my-listings', 'txt_no_activity', 'You haven''t submitted a listing yet.'),
('en', 'user', 'my-listings', 'txt_remove_confirm', 'Are you sure you want to remove this listing?'),
('en', 'user', 'my-profile', 'txt_html_title', 'My Profile'),
('en', 'user', 'my-profile', 'txt_main_title', 'My Profile'),
('en', 'user', 'my-profile', 'txt_fname', 'First Name'),
('en', 'user', 'my-profile', 'txt_lname', 'Last Name'),
('en', 'user', 'my-profile', 'txt_download_data', 'Download Data'),
('en', 'user', 'my-reviews', 'txt_html_title', 'My Reviews'),
('en', 'user', 'my-reviews', 'txt_main_title', 'My Reviews'),
('en', 'user', 'my-reviews', 'txt_remove_review', 'Remove review'),
('en', 'user', 'my-reviews', 'txt_edit_review', 'Edit review'),
('en', 'user', 'my-reviews', 'txt_no_activity', 'You have not reviewed any place yet.'),
('en', 'user', 'my-reviews', 'txt_remove_confirm', 'Are you sure you want to remove this review?'),
('en', 'user', 'password-reset', 'txt_html_title', 'Reset your password'),
('en', 'user', 'password-reset', 'txt_main_title', 'Reset your password'),
('en', 'user', 'password-reset', 'txt_enter_new_pass', 'Enter your new password below'),
('en', 'user', 'password-reset', 'txt_or_login', 'Or'),
('en', 'user', 'password-reset', 'txt_invalid_token', 'Invalid Token'),
('en', 'user', 'password-reset', 'txt_update_success', 'Password updated successfully'),
('en', 'user', 'process-claim', 'txt_html_title', 'Claim Listing'),
('en', 'user', 'process-claim', 'txt_main_title', 'Claim Listing'),
('en', 'user', 'process-claim', 'txt_meta_desc', 'Claim Listing'),
('en', 'user', 'process-claim', 'txt_confirm_claim', 'Confirm your plan'),
('en', 'user', 'process-claim', 'txt_selected_plan', 'Selected Plan'),
('en', 'user', 'process-claim', 'txt_plan_price', 'Price'),
('en', 'user', 'process-claim', 'txt_pay_mercadopago', 'Pagar com Mercadopago'),
('en', 'user', 'process-claim', 'txt_pay_paypal', 'Pay with Paypal'),
('en', 'user', 'process-claim', 'txt_pay_stripe', 'Pay with Stripe'),
('en', 'user', 'process-create-listing', 'txt_html_title', 'Include Listing'),
('en', 'user', 'process-create-listing', 'txt_html_title_free', 'Listing submitted'),
('en', 'user', 'process-create-listing', 'txt_main_title_success', 'Confirm Inclusion'),
('en', 'user', 'process-create-listing', 'txt_main_title_error', 'Inclusion Error'),
('en', 'user', 'process-create-listing', 'txt_main_title_reload', 'Inclusion Error'),
('en', 'user', 'process-create-listing', 'txt_main_title_free', 'Thank you'),
('en', 'user', 'process-create-listing', 'txt_thanks_msg', 'Your listing will be approved soon.'),
('en', 'user', 'process-create-listing', 'txt_thanks_admin', 'Listing submitted.'),
('en', 'user', 'process-create-listing', 'txt_checkout_msg', 'Please check your order details and continue with payment'),
('en', 'user', 'process-create-listing', 'txt_selected_plan', 'Selected plan'),
('en', 'user', 'process-create-listing', 'txt_plan_value', 'Price'),
('en', 'user', 'process-create-listing', 'txt_pay_paypal', 'Pay with Paypal'),
('en', 'user', 'process-create-listing', 'txt_order_details', 'Order Details'),
('en', 'user', 'process-create-listing', 'txt_btn_mercadopago', 'Pay with MercadoPago'),
('en', 'user', 'process-create-listing', 'txt_invalid_email', 'To use Mercadopago you have to define a valid email in the admin dashboard.'),
('en', 'user', 'process-edit-listing', 'txt_html_title', 'Edit Listing'),
('en', 'user', 'process-edit-listing', 'txt_main_title', 'Edit Listing - ''%place_name%'''),
('en', 'user', 'process-edit-listing', 'txt_error_no_permission', 'You don''t have permission to access this page'),
('en', 'user', 'process-edit-listing', 'txt_success', '%place_name% information has been saved.'),
('en', 'user', 'process-edit-pass', 'txt_html_title', 'Change Password'),
('en', 'user', 'process-edit-pass', 'txt_main_title', 'Change Password'),
('en', 'user', 'process-edit-pass', 'txt_success', 'Password changed successfully.'),
('en', 'user', 'process-edit-pass', 'txt_problem', 'Problem writing new password into database.'),
('en', 'user', 'process-edit-pass', 'txt_wrong', 'Current password is wrong.'),
('en', 'user', 'process-edit-pass', 'txt_social', 'Error: You are logged in with a social media account and you cannot set a new password.'),
('en', 'user', 'register', 'txt_html_title', 'Create an Account'),
('en', 'user', 'register', 'txt_main_title', 'Sign up'),
('en', 'user', 'register', 'txt_acct_created', 'Account created!'),
('en', 'user', 'register', 'txt_acct_created_explain', 'Please check your email and click on the confirmation link.'),
('en', 'user', 'register', 'txt_email_exists', 'User already exists'),
('en', 'user', 'register', 'txt_email_exists_explain', 'Sorry, this email is already registered.'),
('en', 'user', 'register', 'txt_fname', 'First Name'),
('en', 'user', 'register', 'txt_has_account', 'Already have an account?'),
('en', 'user', 'register', 'txt_invalid_email', 'Invalid email'),
('en', 'user', 'register', 'txt_invalid_email_explain', 'Mailbox given [] does not comply with RFC 2822'),
('en', 'user', 'register', 'txt_lname', 'Last Name'),
('en', 'user', 'register', 'txt_missing_fields', 'Missing fields'),
('en', 'user', 'register', 'txt_missing_fields_explain', 'You left some of the fields blank. All fields are required.'),
('en', 'user', 'register', 'txt_submit_again', 'Please submit the form again.'),
('en', 'user', 'register-confirm', 'txt_html_title', 'Signup Confirmation'),
('en', 'user', 'register-confirm', 'txt_main_title', 'Signup Confirmation'),
('en', 'user', 'register-confirm', 'txt_confirmation_success', 'Confirmation succeeded.'),
('en', 'user', 'register-confirm', 'txt_sign_in', 'You can now sign in.'),
('en', 'user', 'register-confirm', 'txt_confirmation_fail', 'Confirmation failed.'),
('en', 'user', 'resend-confirmation', 'txt_html_title', 'Resend Confirmation Email'),
('en', 'user', 'resend-confirmation', 'txt_main_title', 'Resend Confirmation Email'),
('en', 'user', 'resend-confirmation', 'txt_wrong_pass', 'Wrong password or email'),
('en', 'user', 'resend-confirmation', 'txt_confirmation_sent', 'Confirmation sent. Please check your email.'),
('en', 'user', 'resend-confirmation', 'txt_mailer_problem', 'Email failed'),
('en', 'user', 'resend-confirmation', 'txt_invalid_email', 'Invalid email'),
('en', 'user', 'select-plan', 'txt_html_title', 'Select a Plan'),
('en', 'user', 'select-plan', 'txt_main_title', 'Select a Plan'),
('en', 'user', 'select-plan', 'txt_month', 'month'),
('en', 'user', 'select-plan', 'txt_buy_now', 'Select'),
('en', 'user', 'select-plan', 'txt_no_plans', 'There are no plans defined.'),
('en', 'user', 'sign-in', 'txt_html_title', 'Sign in'),
('en', 'user', 'sign-in', 'txt_main_title', 'Sign in'),
('en', 'user', 'sign-in', 'txt_wrong_pass', 'Wrong password or email'),
('en', 'user', 'sign-in', 'txt_email_used', 'Your facebook or twitter email is linked to an account on this site. Please login below.'),
('en', 'user', 'sign-in', 'txt_forgot_pass', 'Forgot password?'),
('en', 'user', 'sign-in', 'txt_new_to_site', 'Need an account?'),
('en', 'user', 'sign-in', 'txt_create_account', 'Create an account?'),
('en', 'user', 'sign-in', 'txt_pending_account', 'Account is pending confirmation.'),
('en', 'user', 'sign-in', 'txt_resend_confirmation', 'Resend confirmation email'),
('en', 'user', 'sign-in', 'txt_from_select_plan', 'To include a listing, please login or create an account.'),
('en', 'user', 'sign-in', 'txt_not_registered', 'This email is not registered.'),
('en', 'user', 'sign-out', 'txt_html_title', 'Logging you off'),
('en', 'user', 'sign-out', 'txt_main_title', 'Logging you off'),
('en', 'user', 'sign-out', 'txt_message', 'Please wait a few seconds.'),
('en', 'user', 'thanks', 'txt_html_title', 'Thank you'),
('en', 'user', 'thanks', 'txt_main_title', 'Thank you for your payment!'),
('en', 'user', 'thanks', 'txt_thanks_msg', 'Payment completed successfully and your listing will be approved soon.'),
('en', 'admin', 'admin-global', 'txt_action', 'Action'),
('en', 'admin', 'admin-global', 'txt_active', 'Active'),
('en', 'admin', 'admin-global', 'txt_create_listing', 'Create Listing'),
('en', 'admin', 'admin-global', 'txt_admin_dashboard', 'Admin Dashboard'),
('en', 'admin', 'admin-global', 'txt_approved', 'Approved'),
('en', 'admin', 'admin-global', 'txt_custom_fields', 'Custom Fields'),
('en', 'admin', 'admin-global', 'txt_emails', 'Emails'),
('en', 'admin', 'admin-global', 'txt_empty', 'Empty Trash'),
('en', 'admin', 'admin-global', 'txt_inactive', 'Inactive'),
('en', 'admin', 'admin-global', 'txt_listings', 'Listings'),
('en', 'admin', 'admin-global', 'txt_locations', 'Locations'),
('en', 'admin', 'admin-global', 'txt_optional', 'Optional'),
('en', 'admin', 'admin-global', 'txt_paid', 'Paid'),
('en', 'admin', 'admin-global', 'txt_plans', 'Plans'),
('en', 'admin', 'admin-global', 'txt_restore', 'Restore'),
('en', 'admin', 'admin-global', 'txt_site_settings', 'Site Settings'),
('en', 'admin', 'admin-global', 'txt_slug', 'Slug'),
('en', 'admin', 'admin-global', 'txt_sort', 'Sort'),
('en', 'admin', 'admin-global', 'txt_status', 'Status'),
('en', 'admin', 'admin-global', 'txt_title', 'Title'),
('en', 'admin', 'admin-global', 'txt_tools', 'Tools'),
('en', 'admin', 'admin-global', 'txt_transactions', 'Transactions'),
('en', 'admin', 'admin-global', 'txt_trash', 'Trash'),
('en', 'admin', 'admin-global', 'txt_unpaid', 'Unpaid'),
('en', 'admin', 'admin-global', 'txt_update_success', 'Updated successfully'),
('en', 'admin', 'categories', 'txt_html_title', 'Categories'),
('en', 'admin', 'categories', 'txt_main_title', 'Categories'),
('en', 'admin', 'categories', 'txt_by_name', 'By name'),
('en', 'admin', 'categories', 'txt_by_parent_id', 'By parent id'),
('en', 'admin', 'categories', 'txt_cat_created', 'Category created successfully'),
('en', 'admin', 'categories', 'txt_cat_edited', 'Category edited successfully'),
('en', 'admin', 'categories', 'txt_cat_icon', 'Icon font tag'),
('en', 'admin', 'categories', 'txt_cat_img', 'Category image'),
('en', 'admin', 'categories', 'txt_cat_name', 'Category name'),
('en', 'admin', 'categories', 'txt_cat_name_empty', 'Category name cannot be empty.'),
('en', 'admin', 'categories', 'txt_cat_order', 'Category order (must be a number)'),
('en', 'admin', 'categories', 'txt_cat_removed', 'Category removed'),
('en', 'admin', 'categories', 'txt_cat_slug', 'Category slug'),
('en', 'admin', 'categories', 'txt_create_cat', 'Create Category'),
('en', 'admin', 'categories', 'txt_edit_cat', 'Edit category'),
('en', 'admin', 'categories', 'txt_icon_filename', 'Icon File'),
('en', 'admin', 'categories', 'txt_no_parent', 'None'),
('en', 'admin', 'categories', 'txt_order', 'Order'),
('en', 'admin', 'categories', 'txt_parent_cat', 'Parent category'),
('en', 'admin', 'categories', 'txt_parent_explain', 'Maximum 3 levels deep.'),
('en', 'admin', 'categories', 'txt_parent_id', 'Parent Id'),
('en', 'admin', 'categories', 'txt_plural_name', 'Plural Name'),
('en', 'admin', 'categories', 'txt_remove_cat', 'Remove category'),
('en', 'admin', 'categories', 'txt_remove_warn', 'Are you sure you want to remove this category?'),
('en', 'admin', 'categories-trash', 'txt_html_title', 'Categories - Trash'),
('en', 'admin', 'categories-trash', 'txt_main_title', 'Categories - Trash'),
('en', 'admin', 'categories-trash', 'txt_order', 'Order'),
('en', 'admin', 'categories-trash', 'txt_parent_id', 'Parent Id'),
('en', 'admin', 'categories-trash', 'txt_restore', 'Restore category'),
('en', 'admin', 'categories-trash', 'txt_remove_sure', 'Are you sure you want to remove this category permanently? This action cannot be undone.'),
('en', 'admin', 'categories-trash', 'txt_remove_all_sure', 'Are you sure you want to remove permanently all categories in the trash can? This action cannot be undone.'),
('en', 'admin', 'coupons', 'txt_html_title', 'Coupons'),
('en', 'admin', 'coupons', 'txt_main_title', 'Coupons'),
('en', 'admin', 'coupons', 'txt_title', 'Title'),
('en', 'admin', 'coupons', 'txt_created', 'Created'),
('en', 'admin', 'coupons', 'txt_expire', 'Expire'),
('en', 'admin', 'coupons', 'txt_listing', 'Listing'),
('en', 'admin', 'coupons-trash', 'txt_html_title', 'Coupons Trash'),
('en', 'admin', 'coupons-trash', 'txt_main_title', 'Coupons Trash'),
('en', 'admin', 'coupons-trash', 'txt_created', 'Created'),
('en', 'admin', 'coupons-trash', 'txt_expire', 'Expire'),
('en', 'admin', 'coupons-trash', 'txt_listing', 'Listing'),
('en', 'admin', 'coupons-trash', 'txt_remove', 'Remove permanently'),
('en', 'admin', 'coupons-trash', 'txt_remove_all_sure', 'Are you sure you want to remove all plans in the trash bin? This action cannot be undone.'),
('en', 'admin', 'coupons-trash', 'txt_remove_sure', 'Are you sure you want to remove this coupon? This action cannot be undone.'),
('en', 'admin', 'coupons-trash', 'txt_removed_all', 'All coupons removed'),
('en', 'admin', 'coupons-trash', 'txt_title', 'Title'),
('en', 'admin', 'create-page', 'txt_html_title', 'Create Page'),
('en', 'admin', 'create-page', 'txt_main_title', 'Create Page'),
('en', 'admin', 'create-page', 'txt_page_title', 'Page Title'),
('en', 'admin', 'create-page', 'txt_meta_desc', 'Meta description'),
('en', 'admin', 'create-page', 'txt_order', 'Order'),
('en', 'admin', 'create-page', 'txt_page_created', 'Page created successfully'),
('en', 'admin', 'create-page', 'txt_show_in_blog', 'Show in blog?'),
('en', 'admin', 'create-page', 'txt_enable_comments', 'Enable comments?'),
('en', 'admin', 'create-page', 'txt_thumb', 'Page thumbnail'),
('en', 'admin', 'create-custom-field', 'txt_html_title', 'Create Custom Field'),
('en', 'admin', 'create-custom-field', 'txt_main_title', 'Create Custom Field'),
('en', 'admin', 'create-custom-field', 'txt_categories', 'Categories'),
('en', 'admin', 'create-custom-field', 'txt_field_created', 'Custom field created successfully'),
('en', 'admin', 'create-custom-field', 'txt_field_name', 'Field Name'),
('en', 'admin', 'create-custom-field', 'txt_field_order', 'Field Order'),
('en', 'admin', 'create-custom-field', 'txt_field_type', 'Field Type'),
('en', 'admin', 'create-custom-field', 'txt_filter_display', 'Filter Display As'),
('en', 'admin', 'create-custom-field', 'txt_goto', 'Go to Custom Fields'),
('en', 'admin', 'create-custom-field', 'txt_icon', 'Icon tag (e.g. fontawesome tag) <em>(optional)</em>'),
('en', 'admin', 'create-custom-field', 'txt_options', 'Options'),
('en', 'admin', 'create-custom-field', 'txt_range_number', 'Range Number'),
('en', 'admin', 'create-custom-field', 'txt_range_select', 'Range Select'),
('en', 'admin', 'create-custom-field', 'txt_range_text', 'Range Text'),
('en', 'admin', 'create-custom-field', 'txt_required', 'Required?'),
('en', 'admin', 'create-custom-field', 'txt_searchable', 'Searchable?'),
('en', 'admin', 'create-custom-field', 'txt_select_all', 'Select All'),
('en', 'admin', 'create-custom-field', 'txt_tooltip', 'Tooltip <em>(optional)</em>'),
('en', 'admin', 'create-custom-field', 'txt_type_check', 'Checkbox'),
('en', 'admin', 'create-custom-field', 'txt_type_multiline', 'Text Multiline'),
('en', 'admin', 'create-custom-field', 'txt_type_radio', 'Radio'),
('en', 'admin', 'create-custom-field', 'txt_type_select', 'Select'),
('en', 'admin', 'create-custom-field', 'txt_type_text', 'Text'),
('en', 'admin', 'create-custom-field', 'txt_type_url', 'URL'),
('en', 'admin', 'create-custom-field', 'txt_values_list', 'List of values allowed <em>(separated by ;)</em> *only used for radio, select and checkboxes'),
('en', 'admin', 'custom-fields', 'txt_field_name', 'Field Name'),
('en', 'admin', 'custom-fields', 'txt_field_type', 'Field Type'),
('en', 'admin', 'custom-fields', 'txt_type_text', 'Text'),
('en', 'admin', 'custom-fields', 'txt_type_radio', 'Radio'),
('en', 'admin', 'custom-fields', 'txt_type_select', 'Select'),
('en', 'admin', 'custom-fields', 'txt_type_check', 'Checkbox'),
('en', 'admin', 'custom-fields', 'txt_type_multiline', 'Text Multiline'),
('en', 'admin', 'custom-fields', 'txt_type_url', 'URL'),
('en', 'admin', 'custom-fields', 'txt_values_list', 'List of values allowed <em>(separated by ;)</em> *only used for radio, select and checkboxes'),
('en', 'admin', 'custom-fields', 'txt_tooltip', 'Tooltip <em>(optional)</em>'),
('en', 'admin', 'custom-fields', 'txt_icon', 'Icon tag (e.g. fontawesome tag)'),
('en', 'admin', 'custom-fields', 'txt_options', 'Options'),
('en', 'admin', 'custom-fields', 'txt_required', 'Required?'),
('en', 'admin', 'custom-fields', 'txt_searchable', 'Searchable?'),
('en', 'admin', 'custom-fields', 'txt_field_order', 'Field Order'),
('en', 'admin', 'custom-fields', 'txt_categories', 'Categories'),
('en', 'admin', 'custom-fields', 'txt_show_html_title', 'Custom Fields'),
('en', 'admin', 'custom-fields', 'txt_show_main_title', 'Custom Fields'),
('en', 'admin', 'custom-fields', 'txt_show_create_field', 'Create Field'),
('en', 'admin', 'custom-fields', 'txt_show_edit_field', 'Edit this custom field'),
('en', 'admin', 'custom-fields', 'txt_show_remove_field', 'Remove this custom field'),
('en', 'admin', 'custom-fields', 'txt_field_created', 'Field created'),
('en', 'admin', 'custom-fields', 'txt_create_another', 'Create another field.'),
('en', 'admin', 'custom-fields', 'txt_field_removed', 'Field removed'),
('en', 'admin', 'custom-fields', 'txt_header_custom_fields', 'Additional Information'),
('en', 'admin', 'custom-fields', 'txt_no_custom_fields', 'No custom fields available for this category'),
('en', 'admin', 'custom-fields', 'txt_html_title', 'Custom Fields'),
('en', 'admin', 'custom-fields', 'txt_main_title', 'Custom Fields'),
('en', 'admin', 'custom-fields', 'txt_meta_desc', 'Custom Fields'),
('en', 'admin', 'custom-fields', 'txt_search_results', 'Search Results'),
('en', 'admin', 'custom-fields', 'txt_label_keyword', 'Keyword'),
('en', 'admin', 'custom-fields', 'txt_label_city', 'Select City'),
('en', 'admin', 'custom-fields', 'txt_label_category', 'Select Category'),
('en', 'admin', 'custom-fields', 'txt_label_cat_all', 'Select All'),
('en', 'admin', 'edit-custom-field', 'txt_html_title', 'Edit Custom Field'),
('en', 'admin', 'edit-custom-field', 'txt_main_title', 'Edit Custom Field'),
('en', 'admin', 'edit-custom-field', 'txt_field_name', 'Field name'),
('en', 'admin', 'edit-custom-field', 'txt_field_order', 'Field Order'),
('en', 'admin', 'edit-custom-field', 'txt_field_type', 'Field type'),
('en', 'admin', 'edit-custom-field', 'txt_field_updated', 'Field updated'),
('en', 'admin', 'edit-custom-field', 'txt_filter_display', 'Filter Display As'),
('en', 'admin', 'edit-custom-field', 'txt_icon', 'Icon'),
('en', 'admin', 'edit-custom-field', 'txt_options', 'Options'),
('en', 'admin', 'edit-custom-field', 'txt_range_number', 'Range Number'),
('en', 'admin', 'edit-custom-field', 'txt_range_select', 'Range Select'),
('en', 'admin', 'edit-custom-field', 'txt_range_text', 'Range Text'),
('en', 'admin', 'edit-custom-field', 'txt_searchable', 'Searchable'),
('en', 'admin', 'edit-custom-field', 'txt_select_all', 'Select All'),
('en', 'admin', 'edit-custom-field', 'txt_tooltip', 'Tooltip'),
('en', 'admin', 'edit-custom-field', 'txt_values_list', 'List of values allowed (separated by ;) *only used for radio, select and checkboxes'),
('en', 'admin', 'edit-page', 'txt_html_title', 'Edit Page'),
('en', 'admin', 'edit-page', 'txt_main_title', 'Edit Page'),
('en', 'admin', 'edit-page', 'txt_page_title', 'Page Title'),
('en', 'admin', 'edit-page', 'txt_show_in_blog', 'Show in blog?'),
('en', 'admin', 'edit-page', 'txt_meta_desc', 'Meta description'),
('en', 'admin', 'edit-page', 'txt_enable_comments', 'Enable comments?'),
('en', 'admin', 'edit-page', 'txt_thumb', 'Page thumbnail'),
('en', 'admin', 'emails', 'txt_html_title', 'Email Templates'),
('en', 'admin', 'emails', 'txt_main_title', 'Email Templates'),
('en', 'admin', 'emails', 'txt_type', 'Type'),
('en', 'admin', 'emails', 'txt_description', 'Description'),
('en', 'admin', 'emails', 'txt_edit_template', 'Edit email template'),
('en', 'admin', 'emails', 'txt_no_templates', 'No email templates'),
('en', 'admin', 'emails', 'txt_available_vars_header', 'Available variables'),
('en', 'admin', 'emails', 'txt_email_subject', 'Email Subject'),
('en', 'admin', 'emails', 'txt_email_body', 'Email Body'),
('en', 'admin', 'emails', 'txt_instruct_reset', 'You must include the ''%reset_link%'' token in the email body. It will get replaced by a real link the user will have to click to reset his password'),
('en', 'admin', 'emails', 'txt_instruct_signup', 'You must include the ''%confirm_link%'' token in the email body. It will get replaced by a real link the user will have to click to confirm account creation.'),
('en', 'admin', 'emails', 'txt_email_template_updated', 'Template updated sucessfully'),
('en', 'admin', 'home', 'txt_html_title', 'Admin dashboard'),
('en', 'admin', 'home', 'txt_main_title', 'Admin dashboard'),
('en', 'admin', 'home', 'txt_your_info', 'Your information'),
('en', 'admin', 'home', 'txt_your_id', 'Your id'),
('en', 'admin', 'home', 'txt_your_email', 'Your email'),
('en', 'admin', 'home', 'txt_your_prof', 'Your public profile'),
('en', 'admin', 'home', 'txt_site_stats', 'Site statistics'),
('en', 'admin', 'home', 'txt_pending_mod', 'Listings pending moderation'),
('en', 'admin', 'home', 'txt_total_list', 'Total listings'),
('en', 'admin', 'home', 'txt_total_users', 'Total users'),
('en', 'admin', 'home', 'txt_total_reviews', 'Total reviews'),
('en', 'admin', 'home', 'txt_version', 'Script version'),
('en', 'admin', 'home', 'txt_support', 'Support'),
('en', 'admin', 'home', 'txt_support_req', 'Send request'),
('en', 'admin', 'home', 'txt_latest_listings', 'Latest Listings'),
('en', 'admin', 'home', 'txt_latest_signups', 'Latest Signups'),
('en', 'admin', 'listings', 'txt_html_title', 'Listings'),
('en', 'admin', 'listings', 'txt_main_title', 'Listings'),
('en', 'admin', 'listings', 'txt_by_date', 'By date'),
('en', 'admin', 'listings', 'txt_by_name', 'By name'),
('en', 'admin', 'listings', 'txt_edit_place', 'Edit Listing'),
('en', 'admin', 'listings', 'txt_find', 'Find'),
('en', 'admin', 'listings', 'txt_listing_owner', 'Owner'),
('en', 'admin', 'listings', 'txt_place_name', 'Listing Name'),
('en', 'admin', 'listings', 'txt_plan_name', 'Plan Name'),
('en', 'admin', 'listings', 'txt_plan_type', 'Plan Type'),
('en', 'admin', 'listings', 'txt_place_removed', 'Listing removed successfully'),
('en', 'admin', 'listings', 'txt_remove_place', 'Remove Listing'),
('en', 'admin', 'listings', 'txt_remove_warn', 'Are you sure you want to remove this listing?'),
('en', 'admin', 'listings', 'txt_search_results', 'Search results for:'),
('en', 'admin', 'listings', 'txt_toggle_approved', 'Toggle Approved/Pending'),
('en', 'admin', 'listings', 'txt_toggle_featured', 'Toggle Featured Home'),
('en', 'admin', 'listings', 'txt_toggle_paid', 'Toggle Paid/Unpaid Status'),
('en', 'admin', 'listings', 'txt_tooltip_expand', 'Expand details'),
('en', 'admin', 'listings', 'txt_transfer_owner', 'Transfer to user id: '),
('en', 'admin', 'listings-trash', 'txt_by_date', 'By date'),
('en', 'admin', 'listings-trash', 'txt_by_name', 'By name'),
('en', 'admin', 'listings-trash', 'txt_html_title', 'Manage Listings - Trash'),
('en', 'admin', 'listings-trash', 'txt_listing_owner', 'Owner'),
('en', 'admin', 'listings-trash', 'txt_main_title', 'Manage Listings - Trash'),
('en', 'admin', 'listings-trash', 'txt_place_name', 'Listing name'),
('en', 'admin', 'listings-trash', 'txt_place_removed', 'Listing removed'),
('en', 'admin', 'listings-trash', 'txt_plan_name', 'Plan name'),
('en', 'admin', 'listings-trash', 'txt_plan_type', 'Plan type'),
('en', 'admin', 'listings-trash', 'txt_remove_perm', 'Remove permanently'),
('en', 'admin', 'listings-trash', 'txt_remove_perm_sure', 'Are you sure you want to remove this listing permanently? This action cannot be undone.'),
('en', 'admin', 'listings-trash', 'txt_remove_perm_sure_all', 'Are you sure you want to remove permanently all listings in the trash can? This action cannot be undone.'),
('en', 'admin', 'listings-trash', 'txt_tooltip_expand', 'Expand details'),
('en', 'admin', 'listings-trash', 'txt_tooltip_remove', 'Remove permanently'),
('en', 'admin', 'listings-trash', 'txt_tooltip_restore', 'Restore listing'),
('en', 'admin', 'locations', 'txt_html_title', 'Locations'),
('en', 'admin', 'locations', 'txt_main_title', 'Locations'),
('en', 'admin', 'locations', 'txt_city_id', 'City id'),
('en', 'admin', 'locations', 'txt_city_name', 'City name'),
('en', 'admin', 'locations', 'txt_country_code', 'Country code'),
('en', 'admin', 'locations', 'txt_country_id', 'Country id'),
('en', 'admin', 'locations', 'txt_country_name', 'Country name'),
('en', 'admin', 'locations', 'txt_create_city', 'Create city'),
('en', 'admin', 'locations', 'txt_create_country', 'Create country'),
('en', 'admin', 'locations', 'txt_create_state', 'Create state'),
('en', 'admin', 'locations', 'txt_edit_city', 'Edit city'),
('en', 'admin', 'locations', 'txt_edit_country', 'Edit country'),
('en', 'admin', 'locations', 'txt_edit_location', 'Edit location'),
('en', 'admin', 'locations', 'txt_edit_state', 'Edit state'),
('en', 'admin', 'locations', 'txt_quick_jump', 'Quick jump'),
('en', 'admin', 'locations', 'txt_remove_city', 'Remove city'),
('en', 'admin', 'locations', 'txt_remove_country', 'Remove country'),
('en', 'admin', 'locations', 'txt_remove_state', 'Remove state'),
('en', 'admin', 'locations', 'txt_show', 'Show'),
('en', 'admin', 'locations', 'txt_state_id', 'State id'),
('en', 'admin', 'locations', 'txt_state_name', 'State name'),
('en', 'admin', 'locations', 'txt_toggle_featured', 'Toggle home featured'),
('en', 'admin', 'locations', 'txt_country_abbr', 'Country abbreviation (max 3 chars)'),
('en', 'admin', 'locations', 'txt_lat', 'Latitude'),
('en', 'admin', 'locations', 'txt_lng', 'Longitude'),
('en', 'admin', 'locations', 'txt_msg_no_country', 'No country has been created yet'),
('en', 'admin', 'locations', 'txt_msg_no_state', 'No state has been created yet'),
('en', 'admin', 'locations', 'txt_select_country', 'Select country'),
('en', 'admin', 'locations', 'txt_select_state', 'Select state'),
('en', 'admin', 'locations', 'txt_state_abbr', 'State abbreviation'),
('en', 'admin', 'locations', 'txt_city_created', 'City created successfully'),
('en', 'admin', 'locations', 'txt_city_name_empty', 'City name cannot be empty. Please enter the city name.'),
('en', 'admin', 'locations', 'txt_country_created', 'Country created successfully'),
('en', 'admin', 'locations', 'txt_country_name_empty', 'Country name and abbreviation cannot be empty. Please enter the name and abbreviation.'),
('en', 'admin', 'locations', 'txt_pls_create_country', 'Please create a country first.'),
('en', 'admin', 'locations', 'txt_pls_create_state', 'Please create a state first.'),
('en', 'admin', 'locations', 'txt_state_created', 'State created successfully'),
('en', 'admin', 'locations', 'txt_state_name_empty', 'State name and abbreviation cannot be empty. Please enter the name and abbreviation.'),
('en', 'admin', 'locations', 'txt_city_edited', 'City edited successfully'),
('en', 'admin', 'locations', 'txt_state_edited', 'State edited successfully'),
('en', 'admin', 'locations', 'txt_country_edited', 'Country edited successfully'),
('en', 'admin', 'locations', 'txt_loc_removed', 'Location deleted'),
('en', 'admin', 'locations', 'txt_loc_remove_problem', 'Problem removing location'),
('en', 'admin', 'pages', 'txt_html_title', 'Pages'),
('en', 'admin', 'pages', 'txt_main_title', 'Pages'),
('en', 'admin', 'pages', 'txt_create_page', 'Create page'),
('en', 'admin', 'pages', 'txt_link', 'Link'),
('en', 'admin', 'pages', 'txt_view', 'View'),
('en', 'admin', 'pages', 'txt_edit_page', 'Edit page'),
('en', 'admin', 'pages', 'txt_remove_page', 'Remove page'),
('en', 'admin', 'pages', 'txt_page_created', 'Page created sucessfully'),
('en', 'admin', 'pages', 'txt_page_updated', 'Page updated sucessfully'),
('en', 'admin', 'pages', 'txt_page_removed', 'Page deleted'),
('en', 'admin', 'pages-trash', 'txt_html_title', 'Pages - Trash'),
('en', 'admin', 'pages-trash', 'txt_main_title', 'Pages - Trash'),
('en', 'admin', 'pages-trash', 'txt_page_title', 'Page Title'),
('en', 'admin', 'pages-trash', 'txt_link', 'Link'),
('en', 'admin', 'pages-trash', 'txt_group', 'Group'),
('en', 'admin', 'pages-trash', 'txt_order', 'Order'),
('en', 'admin', 'pages-trash', 'txt_view', 'View'),
('en', 'admin', 'pages-trash', 'txt_remove', 'Remove permanently'),
('en', 'admin', 'pages-trash', 'txt_remove_sure', 'Are you sure you want to remove this page? This action cannot be undone.'),
('en', 'admin', 'pages-trash', 'txt_remove_all_sure', 'Are you sure you want to remove permanently all pages in the trash bin? This action cannot be undone.'),
('en', 'admin', 'pages-trash', 'txt_removed_all', 'All pages removed'),
('en', 'admin', 'plans', 'txt_html_title', 'Billing Plans'),
('en', 'admin', 'plans', 'txt_main_title', 'Billing Plans'),
('en', 'admin', 'plans', 'txt_annual', 'Annual'),
('en', 'admin', 'plans', 'txt_annual_f', 'Annual featured'),
('en', 'admin', 'plans', 'txt_create', 'Create Plan'),
('en', 'admin', 'plans', 'txt_edit_plan', 'Edit Plan'),
('en', 'admin', 'plans', 'txt_features', 'Features (one per line)'),
('en', 'admin', 'plans', 'txt_free', 'Free'),
('en', 'admin', 'plans', 'txt_free_featured', 'Free featured'),
('en', 'admin', 'plans', 'txt_monthly', 'Monthly'),
('en', 'admin', 'plans', 'txt_monthly_f', 'Monthly featured'),
('en', 'admin', 'plans', 'txt_no_plans', 'There are no billing plans defined. Please create a billing plan.'),
('en', 'admin', 'plans', 'txt_one_time', 'One time payment'),
('en', 'admin', 'plans', 'txt_one_time_f', 'One time payment featured');
INSERT INTO `language` (`lang`, `section`, `template`, `var_name`, `translated`) VALUES
('en', 'admin', 'plans', 'txt_order', 'Order (at which they will appear to the user in the Select Plan page)'),
('en', 'admin', 'plans', 'txt_period', 'Plan Period (Number of days. Only valid for free and ''one time payments'' plan types). Enter 0 or leave blank for non expiring ads (permanent)'),
('en', 'admin', 'plans', 'txt_plan_name', 'Plan Name'),
('en', 'admin', 'plans', 'txt_plan_price', 'Plan Price'),
('en', 'admin', 'plans', 'txt_plan_status', 'Plan Status'),
('en', 'admin', 'plans', 'txt_plan_type', 'Plan Type'),
('en', 'admin', 'plans', 'txt_price', 'Price'),
('en', 'admin', 'plans', 'txt_remove_plan', 'Remove Plan'),
('en', 'admin', 'plans', 'txt_toggle_active', 'Toggle Active/Inactive'),
('en', 'admin', 'plans', 'txt_plan_created', 'Plan created successfully'),
('en', 'admin', 'plans', 'txt_create_problem', 'Problem creating plan'),
('en', 'admin', 'plans', 'txt_plan_updated', 'Plan updated sucessfully'),
('en', 'admin', 'plans', 'txt_plan_removed', 'Plan removed'),
('en', 'admin', 'plans', 'txt_plan_period', 'Plan Period (Number of days. Only valid for free or ''one time payments'' plan types)'),
('en', 'admin', 'plans', 'txt_plan_order', 'Plan Order'),
('en', 'admin', 'plans', 'txt_change_price', 'It''s not possible to change the price for the ''free'' plan type'),
('en', 'admin', 'plans-trash', 'txt_html_title', 'Billing Plans - Trash'),
('en', 'admin', 'plans-trash', 'txt_main_title', 'Billing Plans - Trash'),
('en', 'admin', 'plans-trash', 'txt_plan_name', 'Plan Name'),
('en', 'admin', 'plans-trash', 'txt_plan_type', 'Plan Type'),
('en', 'admin', 'plans-trash', 'txt_price', 'Price'),
('en', 'admin', 'plans-trash', 'txt_remove', 'Remove permanently'),
('en', 'admin', 'plans-trash', 'txt_remove_sure', 'Are you sure you want to remove this plan? This action cannot be undone.'),
('en', 'admin', 'plans-trash', 'txt_remove_all_sure', 'Are you sure you want to remove permanently all plans in the trash bin? This action cannot be undone.'),
('en', 'admin', 'plans-trash', 'txt_removed_all', 'All plans removed'),
('en', 'admin', 'process-settings', 'txt_html_title', 'Settings Updated'),
('en', 'admin', 'process-settings', 'txt_main_title', 'Settings'),
('en', 'admin', 'process-settings', 'txt_update_success', 'Settings saved'),
('en', 'admin', 'reviews', 'txt_html_title', 'Reviews'),
('en', 'admin', 'reviews', 'txt_main_title', 'Reviews'),
('en', 'admin', 'reviews', 'txt_place_name', 'Place Name'),
('en', 'admin', 'reviews', 'txt_tooltip_toggle_approved', 'Toggle Approved/Pending'),
('en', 'admin', 'reviews', 'txt_tooltip_expand_review', 'Expand Review'),
('en', 'admin', 'reviews', 'txt_tooltip_remove_review', 'Remove Review'),
('en', 'admin', 'reviews', 'txt_no_reviews_pending', 'There are no reviews pending moderation'),
('en', 'admin', 'reviews-trash', 'txt_html_title', 'Reviews - Trash'),
('en', 'admin', 'reviews-trash', 'txt_main_title', 'Reviews - Trash'),
('en', 'admin', 'reviews-trash', 'txt_empty_trash', 'Empty Reviews Trash'),
('en', 'admin', 'reviews-trash', 'txt_place_name', 'Place name'),
('en', 'admin', 'reviews-trash', 'txt_remove_perm', 'Remove permanently'),
('en', 'admin', 'reviews-trash', 'txt_remove_perm_sure', 'Are you sure you want to remove this review permanently? This action cannot be undone.'),
('en', 'admin', 'reviews-trash', 'txt_remove_perm_sure_all', 'Are you sure you want to remove permanently all reviews in the trash can? This action cannot be undone.'),
('en', 'admin', 'reviews-trash', 'txt_remove_review', 'Remove review'),
('en', 'admin', 'reviews-trash', 'txt_tooltip_expand_review', 'Expand review'),
('en', 'admin', 'reviews-trash', 'txt_tooltip_remove_review', 'Remove review permanently'),
('en', 'admin', 'reviews-trash', 'txt_tooltip_restore', 'Restore review'),
('en', 'admin', 'settings', 'txt_html_title', 'Settings'),
('en', 'admin', 'settings', 'txt_main_title', 'Settings'),
('en', 'admin', 'settings', 'txt_admin_email', 'Admin email'),
('en', 'admin', 'settings', 'txt_contact_business_subject', 'Contact Business Subject'),
('en', 'admin', 'settings', 'txt_contact_user_subject', 'Contact User Subject'),
('en', 'admin', 'settings', 'txt_country_code', 'Country code'),
('en', 'admin', 'settings', 'txt_country_code_explain', 'ISO 3166-1 alpha-2: two-letter country code, will also be used to build canonical urls so don''t change this often'),
('en', 'admin', 'settings', 'txt_country_name', 'Country name'),
('en', 'admin', 'settings', 'txt_currency_code', 'Currency code'),
('en', 'admin', 'settings', 'txt_currency_code_explain', '3-character <a href=''https://en.wikipedia.org/wiki/ISO_4217#Active_codes'' target=''_blank''>ISO-4217</a> currency code. This will be used when sending data to Paypal.'),
('en', 'admin', 'settings', 'txt_currency_symbol', 'Currency symbol'),
('en', 'admin', 'settings', 'txt_default_cat', 'Default category'),
('en', 'admin', 'settings', 'txt_default_city_id', 'Default city id'),
('en', 'admin', 'settings', 'txt_default_city_id_explain', 'The database row id of the default city '),
('en', 'admin', 'settings', 'txt_default_city_slug', 'Default city slug'),
('en', 'admin', 'settings', 'txt_default_city_slug_explain', 'Slugs are used in urls, lower case name of the default city without special characters or spaces(use dash instead)'),
('en', 'admin', 'settings', 'txt_default_coupon_qty', 'Coupons per ad'),
('en', 'admin', 'settings', 'txt_default_lat', 'Default latitude'),
('en', 'admin', 'settings', 'txt_default_lng', 'Default longitude'),
('en', 'admin', 'settings', 'txt_dev_email', 'Dev email'),
('en', 'admin', 'settings', 'txt_disqus_shortname', 'Disqus Shortname'),
('en', 'admin', 'settings', 'txt_facebook_key', 'Facebook API key'),
('en', 'admin', 'settings', 'txt_facebook_key_explain', 'Used for social login.'),
('en', 'admin', 'settings', 'txt_facebook_secret', 'Facebook API Secret'),
('en', 'admin', 'settings', 'txt_gateway_currency', 'Currency '),
('en', 'admin', 'settings', 'txt_gateway_mode', 'Gateway Mode'),
('en', 'admin', 'settings', 'txt_gmaps_key', 'Google maps key'),
('en', 'admin', 'settings', 'txt_gmaps_key_explain', 'This API key is required to display maps using Google Maps'),
('en', 'admin', 'settings', 'txt_here_key', 'HERE App ID'),
('en', 'admin', 'settings', 'txt_here_secret', 'HERE App Code'),
('en', 'admin', 'settings', 'txt_html_lang', 'HTML lang'),
('en', 'admin', 'settings', 'txt_html_lang_explain', 'the value for the html lang attribute'),
('en', 'admin', 'settings', 'txt_items_per_page', 'Items per page'),
('en', 'admin', 'settings', 'txt_items_per_page_explain', 'How many items to show on each results page'),
('en', 'admin', 'settings', 'txt_live', 'Live'),
('en', 'admin', 'settings', 'txt_live_publishable_key', 'Live Publishable Key'),
('en', 'admin', 'settings', 'txt_live_secret_key', 'Live Secret Key'),
('en', 'admin', 'settings', 'txt_mail_after_post', 'Receive notification on post/edit listing?'),
('en', 'admin', 'settings', 'txt_maintenance_mode', 'Maintenance Mode'),
('en', 'admin', 'settings', 'txt_map_provider', 'Map Provider'),
('en', 'admin', 'settings', 'txt_mapbox_secret', 'MapBox Access Token'),
('en', 'admin', 'settings', 'txt_max_pics', 'Max pics'),
('en', 'admin', 'settings', 'txt_max_pics_explain', 'How many pictures can each business upload'),
('en', 'admin', 'settings', 'txt_paypal_checkout_logo_url', 'Paypal Checkout Logo Url'),
('en', 'admin', 'settings', 'txt_paypal_checkout_logo_url_explain', 'The URL of the logo that will be used on the Paypal checkout page.'),
('en', 'admin', 'settings', 'txt_paypal_header', 'Paypal Settings'),
('en', 'admin', 'settings', 'txt_paypal_locale', 'Paypal login page locale'),
('en', 'admin', 'settings', 'txt_paypal_merchant_id', 'Paypal merchant id'),
('en', 'admin', 'settings', 'txt_paypal_mode', 'Paypal mode (live or sandbox)'),
('en', 'admin', 'settings', 'txt_paypal_sandbox_merch_id', 'Paypal Sandbox merchant id'),
('en', 'admin', 'settings', 'txt_sandbox', 'Sandbox'),
('en', 'admin', 'settings', 'txt_site_name', 'Site name'),
('en', 'admin', 'settings', 'txt_smtp_pass', 'SMTP pass'),
('en', 'admin', 'settings', 'txt_smtp_port', 'SMTP port'),
('en', 'admin', 'settings', 'txt_smtp_server', 'SMTP server'),
('en', 'admin', 'settings', 'txt_smtp_user', 'SMTP user'),
('en', 'admin', 'settings', 'txt_stripe_currency_code', '3-Letter ISO Code'),
('en', 'admin', 'settings', 'txt_stripe_header', 'Stripe Settings'),
('en', 'admin', 'settings', 'txt_stripe_test_mode', 'Test'),
('en', 'admin', 'settings', 'txt_tab_apis', 'APIs'),
('en', 'admin', 'settings', 'txt_tab_email', 'Email'),
('en', 'admin', 'settings', 'txt_tab_general', 'General'),
('en', 'admin', 'settings', 'txt_tab_payment', 'Payment'),
('en', 'admin', 'settings', 'txt_test_publishable_key', 'Test Publishable Key'),
('en', 'admin', 'settings', 'txt_test_secret_key', 'Test Secret Key'),
('en', 'admin', 'settings', 'txt_timezone', 'Timezone'),
('en', 'admin', 'settings', 'txt_timezone_explain', 'Enter your timezone. <a href=''http://php.net/manual/en/timezones.php'' target=''_blank''>Click here</a> for a list of possible values.'),
('en', 'admin', 'settings', 'txt_tomtom_secret', 'TomTom Key'),
('en', 'admin', 'settings', 'txt_twitter_key', 'Twitter API key'),
('en', 'admin', 'settings', 'txt_twitter_key_explain', 'Used for social login.'),
('en', 'admin', 'settings', 'txt_twitter_secret', 'Twitter API secret'),
('en', 'admin', 'tools', 'txt_html_title', 'Admin Tools'),
('en', 'admin', 'tools', 'txt_main_title', 'Admin Tools'),
('en', 'admin', 'tools', 'txt_deactivate_expired', 'Deactivate expired listings'),
('en', 'admin', 'tools', 'txt_deactivate_success', 'Expired listings deactivated successfully'),
('en', 'admin', 'tools', 'txt_deactivate_fail', 'Expired listings deactivated failed'),
('en', 'admin', 'tools', 'txt_delete_tmp_pics', 'Delete temp images'),
('en', 'admin', 'tools', 'txt_regenerate_sitemap', 'Regenerate sitemap.xml'),
('en', 'admin', 'tools', 'txt_submit_sitemap', 'Submit sitemap.xml to Google'),
('en', 'admin', 'tools', 'txt_tool', 'Tool'),
('en', 'admin', 'transactions', 'txt_html_title', 'Transactions History'),
('en', 'admin', 'transactions', 'txt_main_title', 'Transactions History'),
('en', 'admin', 'transactions', 'txt_txn_id', 'Txn Id'),
('en', 'admin', 'transactions', 'txt_place_id', 'Place Id'),
('en', 'admin', 'transactions', 'txt_txn_type', 'Txn Type'),
('en', 'admin', 'transactions', 'txt_amount', 'Amount'),
('en', 'admin', 'transactions', 'txt_sub_id', 'Subscr Id'),
('en', 'admin', 'transactions', 'txt_txn_date', 'Txn Date'),
('en', 'admin', 'users', 'txt_html_title', 'Users'),
('en', 'admin', 'users', 'txt_main_title', 'Users'),
('en', 'admin', 'users', 'txt_by_date', 'By date'),
('en', 'admin', 'users', 'txt_by_email', 'By email'),
('en', 'admin', 'users', 'txt_by_name', 'By name'),
('en', 'admin', 'users', 'txt_created', 'Created'),
('en', 'admin', 'users', 'txt_no_users', 'There are no users'),
('en', 'admin', 'users', 'txt_approve_profile_pic', 'Approve Profile Pic'),
('en', 'admin', 'users', 'txt_remove_user', 'Remove User'),
('en', 'admin', 'users-trash', 'txt_html_title', 'Users - Trash'),
('en', 'admin', 'users-trash', 'txt_main_title', 'Users - Trash'),
('en', 'admin', 'users-trash', 'txt_by_date', 'By date'),
('en', 'admin', 'users-trash', 'txt_by_email', 'By email'),
('en', 'admin', 'users-trash', 'txt_by_name', 'By name'),
('en', 'admin', 'users-trash', 'txt_created', 'Created'),
('en', 'admin', 'users-trash', 'txt_modal_remove_title', 'Remove User'),
('en', 'admin', 'users-trash', 'txt_remove_perm_sure', 'Are you sure you want to remove this user permanently? This action cannot be undone.'),
('en', 'admin', 'users-trash', 'txt_remove_perm_sure_all', 'Are you sure you want to remove permanently all users in the trash can? This action cannot be undone.'),
('en', 'admin', 'users-trash', 'txt_tooltip_remove_user', 'Remove user permanently'),
('en', 'admin', 'users-trash', 'txt_tooltip_restore', 'Restore user'),
('en', 'admin', 'admin-global', 'txt_language', 'Language'),
('en', 'admin', 'language', 'txt_main_title', 'Language'),
('en', 'admin', 'language', 'txt_html_title', 'Language'),
('en', 'admin', 'language', 'txt_installed_lang', 'Installed languages'),
('en', 'admin', 'language', 'txt_create_lang', 'Create Language'),
('en', 'admin', 'language', 'txt_template', 'Template'),
('en', 'admin', 'language', 'txt_load_vars', 'Load vars'),
('en', 'admin', 'language', 'txt_vars', 'Vars'),
('en', 'admin', 'language', 'txt_select_lang_create', 'Select language to create'),
('en', 'admin', 'language', 'txt_install_sql', 'Or install from available sql files'),
('en', 'admin', 'language', 'txt_install', 'Install'),
('en', 'admin', 'language', 'txt_installing', 'Installing...'),
('en', 'admin', 'language', 'txt_done', 'Done'),
('en', 'admin', 'language', 'txt_install_lang', 'Install language'),
('en', 'admin', 'custom-fields-trash', 'txt_field_name', 'Field Name'),
('en', 'admin', 'custom-fields-trash', 'txt_field_type', 'Field Type'),
('en', 'admin', 'custom-fields-trash', 'txt_type_text', 'Text'),
('en', 'admin', 'custom-fields-trash', 'txt_type_radio', 'Radio'),
('en', 'admin', 'custom-fields-trash', 'txt_type_select', 'Select'),
('en', 'admin', 'custom-fields-trash', 'txt_type_check', 'Checkbox'),
('en', 'admin', 'custom-fields-trash', 'txt_type_multiline', 'Text Multiline'),
('en', 'admin', 'custom-fields-trash', 'txt_type_url', 'URL'),
('en', 'admin', 'custom-fields-trash', 'txt_values_list', 'List of values allowed <em>(separated by ;)</em> *only used for radio, select and checkboxes'),
('en', 'admin', 'custom-fields-trash', 'txt_tooltip', 'Tooltip <em>(optional)</em>'),
('en', 'admin', 'custom-fields-trash', 'txt_icon', 'Icon tag (e.g. fontawesome tag)'),
('en', 'admin', 'custom-fields-trash', 'txt_options', 'Options'),
('en', 'admin', 'custom-fields-trash', 'txt_required', 'Required?'),
('en', 'admin', 'custom-fields-trash', 'txt_searchable', 'Searchable?'),
('en', 'admin', 'custom-fields-trash', 'txt_field_order', 'Field Order'),
('en', 'admin', 'custom-fields-trash', 'txt_categories', 'Categories'),
('en', 'admin', 'custom-fields-trash', 'txt_show_html_title', 'Custom Fields - Trash'),
('en', 'admin', 'custom-fields-trash', 'txt_show_main_title', 'Custom Fields - Trash'),
('en', 'admin', 'custom-fields-trash', 'txt_show_create_field', 'Create Field'),
('en', 'admin', 'custom-fields-trash', 'txt_show_edit_field', 'Edit this custom field'),
('en', 'admin', 'custom-fields-trash', 'txt_show_remove_field', 'Remove this custom field'),
('en', 'admin', 'custom-fields-trash', 'txt_field_created', 'Field created'),
('en', 'admin', 'custom-fields-trash', 'txt_create_another', 'Create another field.'),
('en', 'admin', 'custom-fields-trash', 'txt_field_removed', 'Field removed'),
('en', 'admin', 'custom-fields-trash', 'txt_header_custom_fields', 'Additional Information'),
('en', 'admin', 'custom-fields-trash', 'txt_no_custom_fields', 'No custom fields available for this category'),
('en', 'admin', 'custom-fields-trash', 'txt_html_title', 'Custom Fields - Trash'),
('en', 'admin', 'custom-fields-trash', 'txt_main_title', 'Custom Fields - Trash'),
('en', 'admin', 'custom-fields-trash', 'txt_meta_desc', 'Custom Fields'),
('en', 'admin', 'custom-fields-trash', 'txt_search_results', 'Search Results'),
('en', 'admin', 'custom-fields-trash', 'txt_label_keyword', 'Keyword'),
('en', 'admin', 'custom-fields-trash', 'txt_label_city', 'Select City'),
('en', 'admin', 'custom-fields-trash', 'txt_label_category', 'Select Category'),
('en', 'admin', 'custom-fields-trash', 'txt_label_cat_all', 'Select All'),
('en', 'admin', 'custom-fields-trash', 'txt_remove_custom_field', 'Remove Custom Field'),
('en', 'admin', 'custom-fields-trash', 'txt_remove_sure', 'Are you sure you want to remove this field? This action cannot be undone.'),
('en', 'admin', 'custom-fields-trash', 'txt_remove_all_sure', 'Are you sure you want to empty the trash bin? This action cannot be undone.'),
('en', 'public', 'maintenance', 'txt_html_title', 'Site Maintenance'),
('en', 'public', 'maintenance', 'txt_message', 'The site will be back soon');
